/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Group object to create.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Apiv4groupsGroup {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("source")
  private String source = null;

  @JsonProperty("allow_reference")
  private Boolean allowReference = null;

  public Apiv4groupsGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The unique group name used for at-mentioning.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Apiv4groupsGroup displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the group which can include spaces.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public Apiv4groupsGroup source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Must be &#x60;custom&#x60;
   * @return source
  **/
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Apiv4groupsGroup allowReference(Boolean allowReference) {
    this.allowReference = allowReference;
    return this;
  }

   /**
   * Must be true
   * @return allowReference
  **/
  public Boolean isAllowReference() {
    return allowReference;
  }

  public void setAllowReference(Boolean allowReference) {
    this.allowReference = allowReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv4groupsGroup apiv4groupsGroup = (Apiv4groupsGroup) o;
    return Objects.equals(this.name, apiv4groupsGroup.name) &&
        Objects.equals(this.displayName, apiv4groupsGroup.displayName) &&
        Objects.equals(this.source, apiv4groupsGroup.source) &&
        Objects.equals(this.allowReference, apiv4groupsGroup.allowReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayName, source, allowReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv4groupsGroup {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    allowReference: ").append(toIndentedString(allowReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
