/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.ChannelNotifyProps;

/**
 * ChannelMember
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ChannelMember {
  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("roles")
  private String roles = null;

  @JsonProperty("last_viewed_at")
  private Long lastViewedAt = null;

  @JsonProperty("msg_count")
  private Integer msgCount = null;

  @JsonProperty("mention_count")
  private Integer mentionCount = null;

  @JsonProperty("notify_props")
  private ChannelNotifyProps notifyProps = null;

  @JsonProperty("last_update_at")
  private Long lastUpdateAt = null;

  public ChannelMember channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * Get channelId
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public ChannelMember userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public ChannelMember roles(String roles) {
    this.roles = roles;
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  public String getRoles() {
    return roles;
  }

  public void setRoles(String roles) {
    this.roles = roles;
  }

  public ChannelMember lastViewedAt(Long lastViewedAt) {
    this.lastViewedAt = lastViewedAt;
    return this;
  }

   /**
   * The time in milliseconds the channel was last viewed by the user
   * @return lastViewedAt
  **/
  public Long getLastViewedAt() {
    return lastViewedAt;
  }

  public void setLastViewedAt(Long lastViewedAt) {
    this.lastViewedAt = lastViewedAt;
  }

  public ChannelMember msgCount(Integer msgCount) {
    this.msgCount = msgCount;
    return this;
  }

   /**
   * Get msgCount
   * @return msgCount
  **/
  public Integer getMsgCount() {
    return msgCount;
  }

  public void setMsgCount(Integer msgCount) {
    this.msgCount = msgCount;
  }

  public ChannelMember mentionCount(Integer mentionCount) {
    this.mentionCount = mentionCount;
    return this;
  }

   /**
   * Get mentionCount
   * @return mentionCount
  **/
  public Integer getMentionCount() {
    return mentionCount;
  }

  public void setMentionCount(Integer mentionCount) {
    this.mentionCount = mentionCount;
  }

  public ChannelMember notifyProps(ChannelNotifyProps notifyProps) {
    this.notifyProps = notifyProps;
    return this;
  }

   /**
   * Get notifyProps
   * @return notifyProps
  **/
  public ChannelNotifyProps getNotifyProps() {
    return notifyProps;
  }

  public void setNotifyProps(ChannelNotifyProps notifyProps) {
    this.notifyProps = notifyProps;
  }

  public ChannelMember lastUpdateAt(Long lastUpdateAt) {
    this.lastUpdateAt = lastUpdateAt;
    return this;
  }

   /**
   * The time in milliseconds the channel member was last updated
   * @return lastUpdateAt
  **/
  public Long getLastUpdateAt() {
    return lastUpdateAt;
  }

  public void setLastUpdateAt(Long lastUpdateAt) {
    this.lastUpdateAt = lastUpdateAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelMember channelMember = (ChannelMember) o;
    return Objects.equals(this.channelId, channelMember.channelId) &&
        Objects.equals(this.userId, channelMember.userId) &&
        Objects.equals(this.roles, channelMember.roles) &&
        Objects.equals(this.lastViewedAt, channelMember.lastViewedAt) &&
        Objects.equals(this.msgCount, channelMember.msgCount) &&
        Objects.equals(this.mentionCount, channelMember.mentionCount) &&
        Objects.equals(this.notifyProps, channelMember.notifyProps) &&
        Objects.equals(this.lastUpdateAt, channelMember.lastUpdateAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, userId, roles, lastViewedAt, msgCount, mentionCount, notifyProps, lastUpdateAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelMember {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    lastViewedAt: ").append(toIndentedString(lastViewedAt)).append("\n");
    sb.append("    msgCount: ").append(toIndentedString(msgCount)).append("\n");
    sb.append("    mentionCount: ").append(toIndentedString(mentionCount)).append("\n");
    sb.append("    notifyProps: ").append(toIndentedString(notifyProps)).append("\n");
    sb.append("    lastUpdateAt: ").append(toIndentedString(lastUpdateAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
