/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChannelIdPatchBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ChannelIdPatchBody {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("purpose")
  private String purpose = null;

  @JsonProperty("header")
  private String header = null;

  public ChannelIdPatchBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The unique handle for the channel, will be present in the channel URL
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ChannelIdPatchBody displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The non-unique UI name for the channel
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ChannelIdPatchBody purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * A short description of the purpose of the channel
   * @return purpose
  **/
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public ChannelIdPatchBody header(String header) {
    this.header = header;
    return this;
  }

   /**
   * Markdown-formatted text to display in the header of the channel
   * @return header
  **/
  public String getHeader() {
    return header;
  }

  public void setHeader(String header) {
    this.header = header;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelIdPatchBody channelIdPatchBody = (ChannelIdPatchBody) o;
    return Objects.equals(this.name, channelIdPatchBody.name) &&
        Objects.equals(this.displayName, channelIdPatchBody.displayName) &&
        Objects.equals(this.purpose, channelIdPatchBody.purpose) &&
        Objects.equals(this.header, channelIdPatchBody.header);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayName, purpose, header);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelIdPatchBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
