/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.ChannelMember;
import com.your.mattermost.url.client.ChannelNotifyProps;

/**
 * ChannelMemberWithTeamData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ChannelMemberWithTeamData extends ChannelMember {
  @JsonProperty("team_display_name")
  private String teamDisplayName = null;

  @JsonProperty("team_name")
  private String teamName = null;

  @JsonProperty("team_update_at")
  private Integer teamUpdateAt = null;

  public ChannelMemberWithTeamData teamDisplayName(String teamDisplayName) {
    this.teamDisplayName = teamDisplayName;
    return this;
  }

   /**
   * The display name of the team to which this channel belongs.
   * @return teamDisplayName
  **/
  public String getTeamDisplayName() {
    return teamDisplayName;
  }

  public void setTeamDisplayName(String teamDisplayName) {
    this.teamDisplayName = teamDisplayName;
  }

  public ChannelMemberWithTeamData teamName(String teamName) {
    this.teamName = teamName;
    return this;
  }

   /**
   * The name of the team to which this channel belongs.
   * @return teamName
  **/
  public String getTeamName() {
    return teamName;
  }

  public void setTeamName(String teamName) {
    this.teamName = teamName;
  }

  public ChannelMemberWithTeamData teamUpdateAt(Integer teamUpdateAt) {
    this.teamUpdateAt = teamUpdateAt;
    return this;
  }

   /**
   * The time at which the team to which this channel belongs was last updated.
   * @return teamUpdateAt
  **/
  public Integer getTeamUpdateAt() {
    return teamUpdateAt;
  }

  public void setTeamUpdateAt(Integer teamUpdateAt) {
    this.teamUpdateAt = teamUpdateAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelMemberWithTeamData channelMemberWithTeamData = (ChannelMemberWithTeamData) o;
    return Objects.equals(this.teamDisplayName, channelMemberWithTeamData.teamDisplayName) &&
        Objects.equals(this.teamName, channelMemberWithTeamData.teamName) &&
        Objects.equals(this.teamUpdateAt, channelMemberWithTeamData.teamUpdateAt) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamDisplayName, teamName, teamUpdateAt, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelMemberWithTeamData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    teamDisplayName: ").append(toIndentedString(teamDisplayName)).append("\n");
    sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
    sb.append("    teamUpdateAt: ").append(toIndentedString(teamUpdateAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
