/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * An object describing group member information in a channel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ChannelMemberCountByGroup {
  @JsonProperty("group_id")
  private String groupId = null;

  @JsonProperty("channel_member_count")
  private BigDecimal channelMemberCount = null;

  @JsonProperty("channel_member_timezones_count")
  private BigDecimal channelMemberTimezonesCount = null;

  public ChannelMemberCountByGroup groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * ID of the group
   * @return groupId
  **/
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public ChannelMemberCountByGroup channelMemberCount(BigDecimal channelMemberCount) {
    this.channelMemberCount = channelMemberCount;
    return this;
  }

   /**
   * Total number of group members in the channel
   * @return channelMemberCount
  **/
  public BigDecimal getChannelMemberCount() {
    return channelMemberCount;
  }

  public void setChannelMemberCount(BigDecimal channelMemberCount) {
    this.channelMemberCount = channelMemberCount;
  }

  public ChannelMemberCountByGroup channelMemberTimezonesCount(BigDecimal channelMemberTimezonesCount) {
    this.channelMemberTimezonesCount = channelMemberTimezonesCount;
    return this;
  }

   /**
   * Total number of unique timezones for the group members in the channel
   * @return channelMemberTimezonesCount
  **/
  public BigDecimal getChannelMemberTimezonesCount() {
    return channelMemberTimezonesCount;
  }

  public void setChannelMemberTimezonesCount(BigDecimal channelMemberTimezonesCount) {
    this.channelMemberTimezonesCount = channelMemberTimezonesCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelMemberCountByGroup channelMemberCountByGroup = (ChannelMemberCountByGroup) o;
    return Objects.equals(this.groupId, channelMemberCountByGroup.groupId) &&
        Objects.equals(this.channelMemberCount, channelMemberCountByGroup.channelMemberCount) &&
        Objects.equals(this.channelMemberTimezonesCount, channelMemberCountByGroup.channelMemberTimezonesCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, channelMemberCount, channelMemberTimezonesCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelMemberCountByGroup {\n");
    
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    channelMemberCount: ").append(toIndentedString(channelMemberCount)).append("\n");
    sb.append("    channelMemberTimezonesCount: ").append(toIndentedString(channelMemberTimezonesCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
