/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChecklistReorderBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ChecklistReorderBody {
  @JsonProperty("item_num")
  private Integer itemNum = null;

  @JsonProperty("new_location")
  private Integer newLocation = null;

  public ChecklistReorderBody itemNum(Integer itemNum) {
    this.itemNum = itemNum;
    return this;
  }

   /**
   * Zero-based index of the item to reorder.
   * @return itemNum
  **/
  public Integer getItemNum() {
    return itemNum;
  }

  public void setItemNum(Integer itemNum) {
    this.itemNum = itemNum;
  }

  public ChecklistReorderBody newLocation(Integer newLocation) {
    this.newLocation = newLocation;
    return this;
  }

   /**
   * Zero-based index of the new place to move the item to.
   * @return newLocation
  **/
  public Integer getNewLocation() {
    return newLocation;
  }

  public void setNewLocation(Integer newLocation) {
    this.newLocation = newLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChecklistReorderBody checklistReorderBody = (ChecklistReorderBody) o;
    return Objects.equals(this.itemNum, checklistReorderBody.itemNum) &&
        Objects.equals(this.newLocation, checklistReorderBody.newLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemNum, newLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChecklistReorderBody {\n");
    
    sb.append("    itemNum: ").append(toIndentedString(itemNum)).append("\n");
    sb.append("    newLocation: ").append(toIndentedString(newLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
