/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CloudCustomerBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class CloudCustomerBody {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("contact_first_name")
  private String contactFirstName = null;

  @JsonProperty("contact_last_name")
  private String contactLastName = null;

  @JsonProperty("num_employees")
  private String numEmployees = null;

  public CloudCustomerBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CloudCustomerBody email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CloudCustomerBody contactFirstName(String contactFirstName) {
    this.contactFirstName = contactFirstName;
    return this;
  }

   /**
   * Get contactFirstName
   * @return contactFirstName
  **/
  public String getContactFirstName() {
    return contactFirstName;
  }

  public void setContactFirstName(String contactFirstName) {
    this.contactFirstName = contactFirstName;
  }

  public CloudCustomerBody contactLastName(String contactLastName) {
    this.contactLastName = contactLastName;
    return this;
  }

   /**
   * Get contactLastName
   * @return contactLastName
  **/
  public String getContactLastName() {
    return contactLastName;
  }

  public void setContactLastName(String contactLastName) {
    this.contactLastName = contactLastName;
  }

  public CloudCustomerBody numEmployees(String numEmployees) {
    this.numEmployees = numEmployees;
    return this;
  }

   /**
   * Get numEmployees
   * @return numEmployees
  **/
  public String getNumEmployees() {
    return numEmployees;
  }

  public void setNumEmployees(String numEmployees) {
    this.numEmployees = numEmployees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudCustomerBody cloudCustomerBody = (CloudCustomerBody) o;
    return Objects.equals(this.name, cloudCustomerBody.name) &&
        Objects.equals(this.email, cloudCustomerBody.email) &&
        Objects.equals(this.contactFirstName, cloudCustomerBody.contactFirstName) &&
        Objects.equals(this.contactLastName, cloudCustomerBody.contactLastName) &&
        Objects.equals(this.numEmployees, cloudCustomerBody.numEmployees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, contactFirstName, contactLastName, numEmployees);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudCustomerBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    contactFirstName: ").append(toIndentedString(contactFirstName)).append("\n");
    sb.append("    contactLastName: ").append(toIndentedString(contactLastName)).append("\n");
    sb.append("    numEmployees: ").append(toIndentedString(numEmployees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
