/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.SlackAttachment;

import java.util.ArrayList;
import java.util.List;
/**
 * CommandResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class CommandResponse {
  @JsonProperty("ResponseType")
  private String responseType = null;

  @JsonProperty("Text")
  private String text = null;

  @JsonProperty("Username")
  private String username = null;

  @JsonProperty("IconURL")
  private String iconURL = null;

  @JsonProperty("GotoLocation")
  private String gotoLocation = null;

  @JsonProperty("Attachments")
  private List<SlackAttachment> attachments = null;

  public CommandResponse responseType(String responseType) {
    this.responseType = responseType;
    return this;
  }

   /**
   * The response type either in_channel or ephemeral
   * @return responseType
  **/
  public String getResponseType() {
    return responseType;
  }

  public void setResponseType(String responseType) {
    this.responseType = responseType;
  }

  public CommandResponse text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public CommandResponse username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public CommandResponse iconURL(String iconURL) {
    this.iconURL = iconURL;
    return this;
  }

   /**
   * Get iconURL
   * @return iconURL
  **/
  public String getIconURL() {
    return iconURL;
  }

  public void setIconURL(String iconURL) {
    this.iconURL = iconURL;
  }

  public CommandResponse gotoLocation(String gotoLocation) {
    this.gotoLocation = gotoLocation;
    return this;
  }

   /**
   * Get gotoLocation
   * @return gotoLocation
  **/
  public String getGotoLocation() {
    return gotoLocation;
  }

  public void setGotoLocation(String gotoLocation) {
    this.gotoLocation = gotoLocation;
  }

  public CommandResponse attachments(List<SlackAttachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public CommandResponse addAttachmentsItem(SlackAttachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  public List<SlackAttachment> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<SlackAttachment> attachments) {
    this.attachments = attachments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandResponse commandResponse = (CommandResponse) o;
    return Objects.equals(this.responseType, commandResponse.responseType) &&
        Objects.equals(this.text, commandResponse.text) &&
        Objects.equals(this.username, commandResponse.username) &&
        Objects.equals(this.iconURL, commandResponse.iconURL) &&
        Objects.equals(this.gotoLocation, commandResponse.gotoLocation) &&
        Objects.equals(this.attachments, commandResponse.attachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseType, text, username, iconURL, gotoLocation, attachments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandResponse {\n");
    
    sb.append("    responseType: ").append(toIndentedString(responseType)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    iconURL: ").append(toIndentedString(iconURL)).append("\n");
    sb.append("    gotoLocation: ").append(toIndentedString(gotoLocation)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
