/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.ConfigAnalyticsSettings;
import com.your.mattermost.url.client.ConfigClusterSettings;
import com.your.mattermost.url.client.ConfigComplianceSettings;
import com.your.mattermost.url.client.ConfigEmailSettings;
import com.your.mattermost.url.client.ConfigFileSettings;
import com.your.mattermost.url.client.ConfigGitLabSettings;
import com.your.mattermost.url.client.ConfigLdapSettings;
import com.your.mattermost.url.client.ConfigLocalizationSettings;
import com.your.mattermost.url.client.ConfigLogSettings;
import com.your.mattermost.url.client.ConfigMetricsSettings;
import com.your.mattermost.url.client.ConfigNativeAppSettings;
import com.your.mattermost.url.client.ConfigPasswordSettings;
import com.your.mattermost.url.client.ConfigPrivacySettings;
import com.your.mattermost.url.client.ConfigRateLimitSettings;
import com.your.mattermost.url.client.ConfigSamlSettings;
import com.your.mattermost.url.client.ConfigServiceSettings;
import com.your.mattermost.url.client.ConfigSqlSettings;
import com.your.mattermost.url.client.ConfigSupportSettings;
import com.your.mattermost.url.client.ConfigTeamSettings;

/**
 * Config
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Config {
  @JsonProperty("ServiceSettings")
  private ConfigServiceSettings serviceSettings = null;

  @JsonProperty("TeamSettings")
  private ConfigTeamSettings teamSettings = null;

  @JsonProperty("SqlSettings")
  private ConfigSqlSettings sqlSettings = null;

  @JsonProperty("LogSettings")
  private ConfigLogSettings logSettings = null;

  @JsonProperty("PasswordSettings")
  private ConfigPasswordSettings passwordSettings = null;

  @JsonProperty("FileSettings")
  private ConfigFileSettings fileSettings = null;

  @JsonProperty("EmailSettings")
  private ConfigEmailSettings emailSettings = null;

  @JsonProperty("RateLimitSettings")
  private ConfigRateLimitSettings rateLimitSettings = null;

  @JsonProperty("PrivacySettings")
  private ConfigPrivacySettings privacySettings = null;

  @JsonProperty("SupportSettings")
  private ConfigSupportSettings supportSettings = null;

  @JsonProperty("GitLabSettings")
  private ConfigGitLabSettings gitLabSettings = null;

  @JsonProperty("GoogleSettings")
  private ConfigGitLabSettings googleSettings = null;

  @JsonProperty("Office365Settings")
  private ConfigGitLabSettings office365Settings = null;

  @JsonProperty("LdapSettings")
  private ConfigLdapSettings ldapSettings = null;

  @JsonProperty("ComplianceSettings")
  private ConfigComplianceSettings complianceSettings = null;

  @JsonProperty("LocalizationSettings")
  private ConfigLocalizationSettings localizationSettings = null;

  @JsonProperty("SamlSettings")
  private ConfigSamlSettings samlSettings = null;

  @JsonProperty("NativeAppSettings")
  private ConfigNativeAppSettings nativeAppSettings = null;

  @JsonProperty("ClusterSettings")
  private ConfigClusterSettings clusterSettings = null;

  @JsonProperty("MetricsSettings")
  private ConfigMetricsSettings metricsSettings = null;

  @JsonProperty("AnalyticsSettings")
  private ConfigAnalyticsSettings analyticsSettings = null;

  public Config serviceSettings(ConfigServiceSettings serviceSettings) {
    this.serviceSettings = serviceSettings;
    return this;
  }

   /**
   * Get serviceSettings
   * @return serviceSettings
  **/
  public ConfigServiceSettings getServiceSettings() {
    return serviceSettings;
  }

  public void setServiceSettings(ConfigServiceSettings serviceSettings) {
    this.serviceSettings = serviceSettings;
  }

  public Config teamSettings(ConfigTeamSettings teamSettings) {
    this.teamSettings = teamSettings;
    return this;
  }

   /**
   * Get teamSettings
   * @return teamSettings
  **/
  public ConfigTeamSettings getTeamSettings() {
    return teamSettings;
  }

  public void setTeamSettings(ConfigTeamSettings teamSettings) {
    this.teamSettings = teamSettings;
  }

  public Config sqlSettings(ConfigSqlSettings sqlSettings) {
    this.sqlSettings = sqlSettings;
    return this;
  }

   /**
   * Get sqlSettings
   * @return sqlSettings
  **/
  public ConfigSqlSettings getSqlSettings() {
    return sqlSettings;
  }

  public void setSqlSettings(ConfigSqlSettings sqlSettings) {
    this.sqlSettings = sqlSettings;
  }

  public Config logSettings(ConfigLogSettings logSettings) {
    this.logSettings = logSettings;
    return this;
  }

   /**
   * Get logSettings
   * @return logSettings
  **/
  public ConfigLogSettings getLogSettings() {
    return logSettings;
  }

  public void setLogSettings(ConfigLogSettings logSettings) {
    this.logSettings = logSettings;
  }

  public Config passwordSettings(ConfigPasswordSettings passwordSettings) {
    this.passwordSettings = passwordSettings;
    return this;
  }

   /**
   * Get passwordSettings
   * @return passwordSettings
  **/
  public ConfigPasswordSettings getPasswordSettings() {
    return passwordSettings;
  }

  public void setPasswordSettings(ConfigPasswordSettings passwordSettings) {
    this.passwordSettings = passwordSettings;
  }

  public Config fileSettings(ConfigFileSettings fileSettings) {
    this.fileSettings = fileSettings;
    return this;
  }

   /**
   * Get fileSettings
   * @return fileSettings
  **/
  public ConfigFileSettings getFileSettings() {
    return fileSettings;
  }

  public void setFileSettings(ConfigFileSettings fileSettings) {
    this.fileSettings = fileSettings;
  }

  public Config emailSettings(ConfigEmailSettings emailSettings) {
    this.emailSettings = emailSettings;
    return this;
  }

   /**
   * Get emailSettings
   * @return emailSettings
  **/
  public ConfigEmailSettings getEmailSettings() {
    return emailSettings;
  }

  public void setEmailSettings(ConfigEmailSettings emailSettings) {
    this.emailSettings = emailSettings;
  }

  public Config rateLimitSettings(ConfigRateLimitSettings rateLimitSettings) {
    this.rateLimitSettings = rateLimitSettings;
    return this;
  }

   /**
   * Get rateLimitSettings
   * @return rateLimitSettings
  **/
  public ConfigRateLimitSettings getRateLimitSettings() {
    return rateLimitSettings;
  }

  public void setRateLimitSettings(ConfigRateLimitSettings rateLimitSettings) {
    this.rateLimitSettings = rateLimitSettings;
  }

  public Config privacySettings(ConfigPrivacySettings privacySettings) {
    this.privacySettings = privacySettings;
    return this;
  }

   /**
   * Get privacySettings
   * @return privacySettings
  **/
  public ConfigPrivacySettings getPrivacySettings() {
    return privacySettings;
  }

  public void setPrivacySettings(ConfigPrivacySettings privacySettings) {
    this.privacySettings = privacySettings;
  }

  public Config supportSettings(ConfigSupportSettings supportSettings) {
    this.supportSettings = supportSettings;
    return this;
  }

   /**
   * Get supportSettings
   * @return supportSettings
  **/
  public ConfigSupportSettings getSupportSettings() {
    return supportSettings;
  }

  public void setSupportSettings(ConfigSupportSettings supportSettings) {
    this.supportSettings = supportSettings;
  }

  public Config gitLabSettings(ConfigGitLabSettings gitLabSettings) {
    this.gitLabSettings = gitLabSettings;
    return this;
  }

   /**
   * Get gitLabSettings
   * @return gitLabSettings
  **/
  public ConfigGitLabSettings getGitLabSettings() {
    return gitLabSettings;
  }

  public void setGitLabSettings(ConfigGitLabSettings gitLabSettings) {
    this.gitLabSettings = gitLabSettings;
  }

  public Config googleSettings(ConfigGitLabSettings googleSettings) {
    this.googleSettings = googleSettings;
    return this;
  }

   /**
   * Get googleSettings
   * @return googleSettings
  **/
  public ConfigGitLabSettings getGoogleSettings() {
    return googleSettings;
  }

  public void setGoogleSettings(ConfigGitLabSettings googleSettings) {
    this.googleSettings = googleSettings;
  }

  public Config office365Settings(ConfigGitLabSettings office365Settings) {
    this.office365Settings = office365Settings;
    return this;
  }

   /**
   * Get office365Settings
   * @return office365Settings
  **/
  public ConfigGitLabSettings getOffice365Settings() {
    return office365Settings;
  }

  public void setOffice365Settings(ConfigGitLabSettings office365Settings) {
    this.office365Settings = office365Settings;
  }

  public Config ldapSettings(ConfigLdapSettings ldapSettings) {
    this.ldapSettings = ldapSettings;
    return this;
  }

   /**
   * Get ldapSettings
   * @return ldapSettings
  **/
  public ConfigLdapSettings getLdapSettings() {
    return ldapSettings;
  }

  public void setLdapSettings(ConfigLdapSettings ldapSettings) {
    this.ldapSettings = ldapSettings;
  }

  public Config complianceSettings(ConfigComplianceSettings complianceSettings) {
    this.complianceSettings = complianceSettings;
    return this;
  }

   /**
   * Get complianceSettings
   * @return complianceSettings
  **/
  public ConfigComplianceSettings getComplianceSettings() {
    return complianceSettings;
  }

  public void setComplianceSettings(ConfigComplianceSettings complianceSettings) {
    this.complianceSettings = complianceSettings;
  }

  public Config localizationSettings(ConfigLocalizationSettings localizationSettings) {
    this.localizationSettings = localizationSettings;
    return this;
  }

   /**
   * Get localizationSettings
   * @return localizationSettings
  **/
  public ConfigLocalizationSettings getLocalizationSettings() {
    return localizationSettings;
  }

  public void setLocalizationSettings(ConfigLocalizationSettings localizationSettings) {
    this.localizationSettings = localizationSettings;
  }

  public Config samlSettings(ConfigSamlSettings samlSettings) {
    this.samlSettings = samlSettings;
    return this;
  }

   /**
   * Get samlSettings
   * @return samlSettings
  **/
  public ConfigSamlSettings getSamlSettings() {
    return samlSettings;
  }

  public void setSamlSettings(ConfigSamlSettings samlSettings) {
    this.samlSettings = samlSettings;
  }

  public Config nativeAppSettings(ConfigNativeAppSettings nativeAppSettings) {
    this.nativeAppSettings = nativeAppSettings;
    return this;
  }

   /**
   * Get nativeAppSettings
   * @return nativeAppSettings
  **/
  public ConfigNativeAppSettings getNativeAppSettings() {
    return nativeAppSettings;
  }

  public void setNativeAppSettings(ConfigNativeAppSettings nativeAppSettings) {
    this.nativeAppSettings = nativeAppSettings;
  }

  public Config clusterSettings(ConfigClusterSettings clusterSettings) {
    this.clusterSettings = clusterSettings;
    return this;
  }

   /**
   * Get clusterSettings
   * @return clusterSettings
  **/
  public ConfigClusterSettings getClusterSettings() {
    return clusterSettings;
  }

  public void setClusterSettings(ConfigClusterSettings clusterSettings) {
    this.clusterSettings = clusterSettings;
  }

  public Config metricsSettings(ConfigMetricsSettings metricsSettings) {
    this.metricsSettings = metricsSettings;
    return this;
  }

   /**
   * Get metricsSettings
   * @return metricsSettings
  **/
  public ConfigMetricsSettings getMetricsSettings() {
    return metricsSettings;
  }

  public void setMetricsSettings(ConfigMetricsSettings metricsSettings) {
    this.metricsSettings = metricsSettings;
  }

  public Config analyticsSettings(ConfigAnalyticsSettings analyticsSettings) {
    this.analyticsSettings = analyticsSettings;
    return this;
  }

   /**
   * Get analyticsSettings
   * @return analyticsSettings
  **/
  public ConfigAnalyticsSettings getAnalyticsSettings() {
    return analyticsSettings;
  }

  public void setAnalyticsSettings(ConfigAnalyticsSettings analyticsSettings) {
    this.analyticsSettings = analyticsSettings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Config config = (Config) o;
    return Objects.equals(this.serviceSettings, config.serviceSettings) &&
        Objects.equals(this.teamSettings, config.teamSettings) &&
        Objects.equals(this.sqlSettings, config.sqlSettings) &&
        Objects.equals(this.logSettings, config.logSettings) &&
        Objects.equals(this.passwordSettings, config.passwordSettings) &&
        Objects.equals(this.fileSettings, config.fileSettings) &&
        Objects.equals(this.emailSettings, config.emailSettings) &&
        Objects.equals(this.rateLimitSettings, config.rateLimitSettings) &&
        Objects.equals(this.privacySettings, config.privacySettings) &&
        Objects.equals(this.supportSettings, config.supportSettings) &&
        Objects.equals(this.gitLabSettings, config.gitLabSettings) &&
        Objects.equals(this.googleSettings, config.googleSettings) &&
        Objects.equals(this.office365Settings, config.office365Settings) &&
        Objects.equals(this.ldapSettings, config.ldapSettings) &&
        Objects.equals(this.complianceSettings, config.complianceSettings) &&
        Objects.equals(this.localizationSettings, config.localizationSettings) &&
        Objects.equals(this.samlSettings, config.samlSettings) &&
        Objects.equals(this.nativeAppSettings, config.nativeAppSettings) &&
        Objects.equals(this.clusterSettings, config.clusterSettings) &&
        Objects.equals(this.metricsSettings, config.metricsSettings) &&
        Objects.equals(this.analyticsSettings, config.analyticsSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceSettings, teamSettings, sqlSettings, logSettings, passwordSettings, fileSettings, emailSettings, rateLimitSettings, privacySettings, supportSettings, gitLabSettings, googleSettings, office365Settings, ldapSettings, complianceSettings, localizationSettings, samlSettings, nativeAppSettings, clusterSettings, metricsSettings, analyticsSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Config {\n");
    
    sb.append("    serviceSettings: ").append(toIndentedString(serviceSettings)).append("\n");
    sb.append("    teamSettings: ").append(toIndentedString(teamSettings)).append("\n");
    sb.append("    sqlSettings: ").append(toIndentedString(sqlSettings)).append("\n");
    sb.append("    logSettings: ").append(toIndentedString(logSettings)).append("\n");
    sb.append("    passwordSettings: ").append(toIndentedString(passwordSettings)).append("\n");
    sb.append("    fileSettings: ").append(toIndentedString(fileSettings)).append("\n");
    sb.append("    emailSettings: ").append(toIndentedString(emailSettings)).append("\n");
    sb.append("    rateLimitSettings: ").append(toIndentedString(rateLimitSettings)).append("\n");
    sb.append("    privacySettings: ").append(toIndentedString(privacySettings)).append("\n");
    sb.append("    supportSettings: ").append(toIndentedString(supportSettings)).append("\n");
    sb.append("    gitLabSettings: ").append(toIndentedString(gitLabSettings)).append("\n");
    sb.append("    googleSettings: ").append(toIndentedString(googleSettings)).append("\n");
    sb.append("    office365Settings: ").append(toIndentedString(office365Settings)).append("\n");
    sb.append("    ldapSettings: ").append(toIndentedString(ldapSettings)).append("\n");
    sb.append("    complianceSettings: ").append(toIndentedString(complianceSettings)).append("\n");
    sb.append("    localizationSettings: ").append(toIndentedString(localizationSettings)).append("\n");
    sb.append("    samlSettings: ").append(toIndentedString(samlSettings)).append("\n");
    sb.append("    nativeAppSettings: ").append(toIndentedString(nativeAppSettings)).append("\n");
    sb.append("    clusterSettings: ").append(toIndentedString(clusterSettings)).append("\n");
    sb.append("    metricsSettings: ").append(toIndentedString(metricsSettings)).append("\n");
    sb.append("    analyticsSettings: ").append(toIndentedString(analyticsSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
