/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ConfigClusterSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ConfigClusterSettings {
  @JsonProperty("Enable")
  private Boolean enable = null;

  @JsonProperty("InterNodeListenAddress")
  private String interNodeListenAddress = null;

  @JsonProperty("InterNodeUrls")
  private List<String> interNodeUrls = null;

  public ConfigClusterSettings enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public ConfigClusterSettings interNodeListenAddress(String interNodeListenAddress) {
    this.interNodeListenAddress = interNodeListenAddress;
    return this;
  }

   /**
   * Get interNodeListenAddress
   * @return interNodeListenAddress
  **/
  public String getInterNodeListenAddress() {
    return interNodeListenAddress;
  }

  public void setInterNodeListenAddress(String interNodeListenAddress) {
    this.interNodeListenAddress = interNodeListenAddress;
  }

  public ConfigClusterSettings interNodeUrls(List<String> interNodeUrls) {
    this.interNodeUrls = interNodeUrls;
    return this;
  }

  public ConfigClusterSettings addInterNodeUrlsItem(String interNodeUrlsItem) {
    if (this.interNodeUrls == null) {
      this.interNodeUrls = new ArrayList<>();
    }
    this.interNodeUrls.add(interNodeUrlsItem);
    return this;
  }

   /**
   * Get interNodeUrls
   * @return interNodeUrls
  **/
  public List<String> getInterNodeUrls() {
    return interNodeUrls;
  }

  public void setInterNodeUrls(List<String> interNodeUrls) {
    this.interNodeUrls = interNodeUrls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigClusterSettings configClusterSettings = (ConfigClusterSettings) o;
    return Objects.equals(this.enable, configClusterSettings.enable) &&
        Objects.equals(this.interNodeListenAddress, configClusterSettings.interNodeListenAddress) &&
        Objects.equals(this.interNodeUrls, configClusterSettings.interNodeUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, interNodeListenAddress, interNodeUrls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigClusterSettings {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    interNodeListenAddress: ").append(toIndentedString(interNodeListenAddress)).append("\n");
    sb.append("    interNodeUrls: ").append(toIndentedString(interNodeUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
