/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConfigNativeAppSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ConfigNativeAppSettings {
  @JsonProperty("AppDownloadLink")
  private String appDownloadLink = null;

  @JsonProperty("AndroidAppDownloadLink")
  private String androidAppDownloadLink = null;

  @JsonProperty("IosAppDownloadLink")
  private String iosAppDownloadLink = null;

  public ConfigNativeAppSettings appDownloadLink(String appDownloadLink) {
    this.appDownloadLink = appDownloadLink;
    return this;
  }

   /**
   * Get appDownloadLink
   * @return appDownloadLink
  **/
  public String getAppDownloadLink() {
    return appDownloadLink;
  }

  public void setAppDownloadLink(String appDownloadLink) {
    this.appDownloadLink = appDownloadLink;
  }

  public ConfigNativeAppSettings androidAppDownloadLink(String androidAppDownloadLink) {
    this.androidAppDownloadLink = androidAppDownloadLink;
    return this;
  }

   /**
   * Get androidAppDownloadLink
   * @return androidAppDownloadLink
  **/
  public String getAndroidAppDownloadLink() {
    return androidAppDownloadLink;
  }

  public void setAndroidAppDownloadLink(String androidAppDownloadLink) {
    this.androidAppDownloadLink = androidAppDownloadLink;
  }

  public ConfigNativeAppSettings iosAppDownloadLink(String iosAppDownloadLink) {
    this.iosAppDownloadLink = iosAppDownloadLink;
    return this;
  }

   /**
   * Get iosAppDownloadLink
   * @return iosAppDownloadLink
  **/
  public String getIosAppDownloadLink() {
    return iosAppDownloadLink;
  }

  public void setIosAppDownloadLink(String iosAppDownloadLink) {
    this.iosAppDownloadLink = iosAppDownloadLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigNativeAppSettings configNativeAppSettings = (ConfigNativeAppSettings) o;
    return Objects.equals(this.appDownloadLink, configNativeAppSettings.appDownloadLink) &&
        Objects.equals(this.androidAppDownloadLink, configNativeAppSettings.androidAppDownloadLink) &&
        Objects.equals(this.iosAppDownloadLink, configNativeAppSettings.iosAppDownloadLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appDownloadLink, androidAppDownloadLink, iosAppDownloadLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigNativeAppSettings {\n");
    
    sb.append("    appDownloadLink: ").append(toIndentedString(appDownloadLink)).append("\n");
    sb.append("    androidAppDownloadLink: ").append(toIndentedString(androidAppDownloadLink)).append("\n");
    sb.append("    iosAppDownloadLink: ").append(toIndentedString(iosAppDownloadLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
