/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConfigSupportSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ConfigSupportSettings {
  @JsonProperty("TermsOfServiceLink")
  private String termsOfServiceLink = null;

  @JsonProperty("PrivacyPolicyLink")
  private String privacyPolicyLink = null;

  @JsonProperty("AboutLink")
  private String aboutLink = null;

  @JsonProperty("HelpLink")
  private String helpLink = null;

  @JsonProperty("ReportAProblemLink")
  private String reportAProblemLink = null;

  @JsonProperty("SupportEmail")
  private String supportEmail = null;

  public ConfigSupportSettings termsOfServiceLink(String termsOfServiceLink) {
    this.termsOfServiceLink = termsOfServiceLink;
    return this;
  }

   /**
   * Get termsOfServiceLink
   * @return termsOfServiceLink
  **/
  public String getTermsOfServiceLink() {
    return termsOfServiceLink;
  }

  public void setTermsOfServiceLink(String termsOfServiceLink) {
    this.termsOfServiceLink = termsOfServiceLink;
  }

  public ConfigSupportSettings privacyPolicyLink(String privacyPolicyLink) {
    this.privacyPolicyLink = privacyPolicyLink;
    return this;
  }

   /**
   * Get privacyPolicyLink
   * @return privacyPolicyLink
  **/
  public String getPrivacyPolicyLink() {
    return privacyPolicyLink;
  }

  public void setPrivacyPolicyLink(String privacyPolicyLink) {
    this.privacyPolicyLink = privacyPolicyLink;
  }

  public ConfigSupportSettings aboutLink(String aboutLink) {
    this.aboutLink = aboutLink;
    return this;
  }

   /**
   * Get aboutLink
   * @return aboutLink
  **/
  public String getAboutLink() {
    return aboutLink;
  }

  public void setAboutLink(String aboutLink) {
    this.aboutLink = aboutLink;
  }

  public ConfigSupportSettings helpLink(String helpLink) {
    this.helpLink = helpLink;
    return this;
  }

   /**
   * Get helpLink
   * @return helpLink
  **/
  public String getHelpLink() {
    return helpLink;
  }

  public void setHelpLink(String helpLink) {
    this.helpLink = helpLink;
  }

  public ConfigSupportSettings reportAProblemLink(String reportAProblemLink) {
    this.reportAProblemLink = reportAProblemLink;
    return this;
  }

   /**
   * Get reportAProblemLink
   * @return reportAProblemLink
  **/
  public String getReportAProblemLink() {
    return reportAProblemLink;
  }

  public void setReportAProblemLink(String reportAProblemLink) {
    this.reportAProblemLink = reportAProblemLink;
  }

  public ConfigSupportSettings supportEmail(String supportEmail) {
    this.supportEmail = supportEmail;
    return this;
  }

   /**
   * Get supportEmail
   * @return supportEmail
  **/
  public String getSupportEmail() {
    return supportEmail;
  }

  public void setSupportEmail(String supportEmail) {
    this.supportEmail = supportEmail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigSupportSettings configSupportSettings = (ConfigSupportSettings) o;
    return Objects.equals(this.termsOfServiceLink, configSupportSettings.termsOfServiceLink) &&
        Objects.equals(this.privacyPolicyLink, configSupportSettings.privacyPolicyLink) &&
        Objects.equals(this.aboutLink, configSupportSettings.aboutLink) &&
        Objects.equals(this.helpLink, configSupportSettings.helpLink) &&
        Objects.equals(this.reportAProblemLink, configSupportSettings.reportAProblemLink) &&
        Objects.equals(this.supportEmail, configSupportSettings.supportEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(termsOfServiceLink, privacyPolicyLink, aboutLink, helpLink, reportAProblemLink, supportEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigSupportSettings {\n");
    
    sb.append("    termsOfServiceLink: ").append(toIndentedString(termsOfServiceLink)).append("\n");
    sb.append("    privacyPolicyLink: ").append(toIndentedString(privacyPolicyLink)).append("\n");
    sb.append("    aboutLink: ").append(toIndentedString(aboutLink)).append("\n");
    sb.append("    helpLink: ").append(toIndentedString(helpLink)).append("\n");
    sb.append("    reportAProblemLink: ").append(toIndentedString(reportAProblemLink)).append("\n");
    sb.append("    supportEmail: ").append(toIndentedString(supportEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
