/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CustomRecentBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class CustomRecentBody {
  @JsonProperty("emoji")
  private String emoji = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("expires_at")
  private String expiresAt = null;

  public CustomRecentBody emoji(String emoji) {
    this.emoji = emoji;
    return this;
  }

   /**
   * Any emoji
   * @return emoji
  **/
  public String getEmoji() {
    return emoji;
  }

  public void setEmoji(String emoji) {
    this.emoji = emoji;
  }

  public CustomRecentBody text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Any custom status text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public CustomRecentBody duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration of custom status, can be &#x60;thirty_minutes&#x60;, &#x60;one_hour&#x60;, &#x60;four_hours&#x60;, &#x60;today&#x60;, &#x60;this_week&#x60; or &#x60;date_and_time&#x60;
   * @return duration
  **/
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public CustomRecentBody expiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * The time at which custom status should be expired. It should be in ISO format.
   * @return expiresAt
  **/
  public String getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomRecentBody customRecentBody = (CustomRecentBody) o;
    return Objects.equals(this.emoji, customRecentBody.emoji) &&
        Objects.equals(this.text, customRecentBody.text) &&
        Objects.equals(this.duration, customRecentBody.duration) &&
        Objects.equals(this.expiresAt, customRecentBody.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emoji, text, duration, expiresAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomRecentBody {\n");
    
    sb.append("    emoji: ").append(toIndentedString(emoji)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
