/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.DataRetentionPolicy;

/**
 * DataRetentionPolicyWithTeamAndChannelCounts
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class DataRetentionPolicyWithTeamAndChannelCounts extends DataRetentionPolicy {
  @JsonProperty("team_count")
  private Integer teamCount = null;

  @JsonProperty("channel_count")
  private Integer channelCount = null;

  public DataRetentionPolicyWithTeamAndChannelCounts teamCount(Integer teamCount) {
    this.teamCount = teamCount;
    return this;
  }

   /**
   * The number of teams to which this policy is applied.
   * @return teamCount
  **/
  public Integer getTeamCount() {
    return teamCount;
  }

  public void setTeamCount(Integer teamCount) {
    this.teamCount = teamCount;
  }

  public DataRetentionPolicyWithTeamAndChannelCounts channelCount(Integer channelCount) {
    this.channelCount = channelCount;
    return this;
  }

   /**
   * The number of channels to which this policy is applied.
   * @return channelCount
  **/
  public Integer getChannelCount() {
    return channelCount;
  }

  public void setChannelCount(Integer channelCount) {
    this.channelCount = channelCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataRetentionPolicyWithTeamAndChannelCounts dataRetentionPolicyWithTeamAndChannelCounts = (DataRetentionPolicyWithTeamAndChannelCounts) o;
    return Objects.equals(this.teamCount, dataRetentionPolicyWithTeamAndChannelCounts.teamCount) &&
        Objects.equals(this.channelCount, dataRetentionPolicyWithTeamAndChannelCounts.channelCount) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamCount, channelCount, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataRetentionPolicyWithTeamAndChannelCounts {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    teamCount: ").append(toIndentedString(teamCount)).append("\n");
    sb.append("    channelCount: ").append(toIndentedString(channelCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
