/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.DataRetentionPolicyWithoutId;

import java.util.ArrayList;
import java.util.List;
/**
 * DataRetentionPolicyWithTeamAndChannelIds
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class DataRetentionPolicyWithTeamAndChannelIds extends DataRetentionPolicyWithoutId {
  @JsonProperty("team_ids")
  private List<String> teamIds = null;

  @JsonProperty("channel_ids")
  private List<String> channelIds = null;

  public DataRetentionPolicyWithTeamAndChannelIds teamIds(List<String> teamIds) {
    this.teamIds = teamIds;
    return this;
  }

  public DataRetentionPolicyWithTeamAndChannelIds addTeamIdsItem(String teamIdsItem) {
    if (this.teamIds == null) {
      this.teamIds = new ArrayList<>();
    }
    this.teamIds.add(teamIdsItem);
    return this;
  }

   /**
   * The IDs of the teams to which this policy should be applied.
   * @return teamIds
  **/
  public List<String> getTeamIds() {
    return teamIds;
  }

  public void setTeamIds(List<String> teamIds) {
    this.teamIds = teamIds;
  }

  public DataRetentionPolicyWithTeamAndChannelIds channelIds(List<String> channelIds) {
    this.channelIds = channelIds;
    return this;
  }

  public DataRetentionPolicyWithTeamAndChannelIds addChannelIdsItem(String channelIdsItem) {
    if (this.channelIds == null) {
      this.channelIds = new ArrayList<>();
    }
    this.channelIds.add(channelIdsItem);
    return this;
  }

   /**
   * The IDs of the channels to which this policy should be applied.
   * @return channelIds
  **/
  public List<String> getChannelIds() {
    return channelIds;
  }

  public void setChannelIds(List<String> channelIds) {
    this.channelIds = channelIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataRetentionPolicyWithTeamAndChannelIds dataRetentionPolicyWithTeamAndChannelIds = (DataRetentionPolicyWithTeamAndChannelIds) o;
    return Objects.equals(this.teamIds, dataRetentionPolicyWithTeamAndChannelIds.teamIds) &&
        Objects.equals(this.channelIds, dataRetentionPolicyWithTeamAndChannelIds.channelIds) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamIds, channelIds, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataRetentionPolicyWithTeamAndChannelIds {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    teamIds: ").append(toIndentedString(teamIds)).append("\n");
    sb.append("    channelIds: ").append(toIndentedString(channelIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
