/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.Apiv4actionsdialogsopenDialog;

/**
 * DialogsOpenBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class DialogsOpenBody {
  @JsonProperty("trigger_id")
  private String triggerId = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("dialog")
  private Apiv4actionsdialogsopenDialog dialog = null;

  public DialogsOpenBody triggerId(String triggerId) {
    this.triggerId = triggerId;
    return this;
  }

   /**
   * Trigger ID provided by other action
   * @return triggerId
  **/
  public String getTriggerId() {
    return triggerId;
  }

  public void setTriggerId(String triggerId) {
    this.triggerId = triggerId;
  }

  public DialogsOpenBody url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL to send the submitted dialog payload to
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public DialogsOpenBody dialog(Apiv4actionsdialogsopenDialog dialog) {
    this.dialog = dialog;
    return this;
  }

   /**
   * Get dialog
   * @return dialog
  **/
  public Apiv4actionsdialogsopenDialog getDialog() {
    return dialog;
  }

  public void setDialog(Apiv4actionsdialogsopenDialog dialog) {
    this.dialog = dialog;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DialogsOpenBody dialogsOpenBody = (DialogsOpenBody) o;
    return Objects.equals(this.triggerId, dialogsOpenBody.triggerId) &&
        Objects.equals(this.url, dialogsOpenBody.url) &&
        Objects.equals(this.dialog, dialogsOpenBody.dialog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(triggerId, url, dialog);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DialogsOpenBody {\n");
    
    sb.append("    triggerId: ").append(toIndentedString(triggerId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    dialog: ").append(toIndentedString(dialog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
