/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Emoji
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Emoji {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("creator_id")
  private String creatorId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("update_at")
  private Long updateAt = null;

  @JsonProperty("delete_at")
  private Long deleteAt = null;

  public Emoji id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the emoji
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Emoji creatorId(String creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * The ID of the user that made the emoji
   * @return creatorId
  **/
  public String getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId;
  }

  public Emoji name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the emoji
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Emoji createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time in milliseconds the emoji was made
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public Emoji updateAt(Long updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * The time in milliseconds the emoji was last updated
   * @return updateAt
  **/
  public Long getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Long updateAt) {
    this.updateAt = updateAt;
  }

  public Emoji deleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * The time in milliseconds the emoji was deleted
   * @return deleteAt
  **/
  public Long getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Emoji emoji = (Emoji) o;
    return Objects.equals(this.id, emoji.id) &&
        Objects.equals(this.creatorId, emoji.creatorId) &&
        Objects.equals(this.name, emoji.name) &&
        Objects.equals(this.createAt, emoji.createAt) &&
        Objects.equals(this.updateAt, emoji.updateAt) &&
        Objects.equals(this.deleteAt, emoji.deleteAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creatorId, name, createAt, updateAt, deleteAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emoji {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
