/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnvironmentConfigGitLabSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class EnvironmentConfigGitLabSettings {
  @JsonProperty("Enable")
  private Boolean enable = null;

  @JsonProperty("Secret")
  private Boolean secret = null;

  @JsonProperty("Id")
  private Boolean id = null;

  @JsonProperty("Scope")
  private Boolean scope = null;

  @JsonProperty("AuthEndpoint")
  private Boolean authEndpoint = null;

  @JsonProperty("TokenEndpoint")
  private Boolean tokenEndpoint = null;

  @JsonProperty("UserApiEndpoint")
  private Boolean userApiEndpoint = null;

  public EnvironmentConfigGitLabSettings enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public EnvironmentConfigGitLabSettings secret(Boolean secret) {
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  public Boolean isSecret() {
    return secret;
  }

  public void setSecret(Boolean secret) {
    this.secret = secret;
  }

  public EnvironmentConfigGitLabSettings id(Boolean id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Boolean isId() {
    return id;
  }

  public void setId(Boolean id) {
    this.id = id;
  }

  public EnvironmentConfigGitLabSettings scope(Boolean scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  public Boolean isScope() {
    return scope;
  }

  public void setScope(Boolean scope) {
    this.scope = scope;
  }

  public EnvironmentConfigGitLabSettings authEndpoint(Boolean authEndpoint) {
    this.authEndpoint = authEndpoint;
    return this;
  }

   /**
   * Get authEndpoint
   * @return authEndpoint
  **/
  public Boolean isAuthEndpoint() {
    return authEndpoint;
  }

  public void setAuthEndpoint(Boolean authEndpoint) {
    this.authEndpoint = authEndpoint;
  }

  public EnvironmentConfigGitLabSettings tokenEndpoint(Boolean tokenEndpoint) {
    this.tokenEndpoint = tokenEndpoint;
    return this;
  }

   /**
   * Get tokenEndpoint
   * @return tokenEndpoint
  **/
  public Boolean isTokenEndpoint() {
    return tokenEndpoint;
  }

  public void setTokenEndpoint(Boolean tokenEndpoint) {
    this.tokenEndpoint = tokenEndpoint;
  }

  public EnvironmentConfigGitLabSettings userApiEndpoint(Boolean userApiEndpoint) {
    this.userApiEndpoint = userApiEndpoint;
    return this;
  }

   /**
   * Get userApiEndpoint
   * @return userApiEndpoint
  **/
  public Boolean isUserApiEndpoint() {
    return userApiEndpoint;
  }

  public void setUserApiEndpoint(Boolean userApiEndpoint) {
    this.userApiEndpoint = userApiEndpoint;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentConfigGitLabSettings environmentConfigGitLabSettings = (EnvironmentConfigGitLabSettings) o;
    return Objects.equals(this.enable, environmentConfigGitLabSettings.enable) &&
        Objects.equals(this.secret, environmentConfigGitLabSettings.secret) &&
        Objects.equals(this.id, environmentConfigGitLabSettings.id) &&
        Objects.equals(this.scope, environmentConfigGitLabSettings.scope) &&
        Objects.equals(this.authEndpoint, environmentConfigGitLabSettings.authEndpoint) &&
        Objects.equals(this.tokenEndpoint, environmentConfigGitLabSettings.tokenEndpoint) &&
        Objects.equals(this.userApiEndpoint, environmentConfigGitLabSettings.userApiEndpoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, secret, id, scope, authEndpoint, tokenEndpoint, userApiEndpoint);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentConfigGitLabSettings {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    authEndpoint: ").append(toIndentedString(authEndpoint)).append("\n");
    sb.append("    tokenEndpoint: ").append(toIndentedString(tokenEndpoint)).append("\n");
    sb.append("    userApiEndpoint: ").append(toIndentedString(userApiEndpoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
