/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnvironmentConfigLogSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class EnvironmentConfigLogSettings {
  @JsonProperty("EnableConsole")
  private Boolean enableConsole = null;

  @JsonProperty("ConsoleLevel")
  private Boolean consoleLevel = null;

  @JsonProperty("EnableFile")
  private Boolean enableFile = null;

  @JsonProperty("FileLevel")
  private Boolean fileLevel = null;

  @JsonProperty("FileLocation")
  private Boolean fileLocation = null;

  @JsonProperty("EnableWebhookDebugging")
  private Boolean enableWebhookDebugging = null;

  @JsonProperty("EnableDiagnostics")
  private Boolean enableDiagnostics = null;

  public EnvironmentConfigLogSettings enableConsole(Boolean enableConsole) {
    this.enableConsole = enableConsole;
    return this;
  }

   /**
   * Get enableConsole
   * @return enableConsole
  **/
  public Boolean isEnableConsole() {
    return enableConsole;
  }

  public void setEnableConsole(Boolean enableConsole) {
    this.enableConsole = enableConsole;
  }

  public EnvironmentConfigLogSettings consoleLevel(Boolean consoleLevel) {
    this.consoleLevel = consoleLevel;
    return this;
  }

   /**
   * Get consoleLevel
   * @return consoleLevel
  **/
  public Boolean isConsoleLevel() {
    return consoleLevel;
  }

  public void setConsoleLevel(Boolean consoleLevel) {
    this.consoleLevel = consoleLevel;
  }

  public EnvironmentConfigLogSettings enableFile(Boolean enableFile) {
    this.enableFile = enableFile;
    return this;
  }

   /**
   * Get enableFile
   * @return enableFile
  **/
  public Boolean isEnableFile() {
    return enableFile;
  }

  public void setEnableFile(Boolean enableFile) {
    this.enableFile = enableFile;
  }

  public EnvironmentConfigLogSettings fileLevel(Boolean fileLevel) {
    this.fileLevel = fileLevel;
    return this;
  }

   /**
   * Get fileLevel
   * @return fileLevel
  **/
  public Boolean isFileLevel() {
    return fileLevel;
  }

  public void setFileLevel(Boolean fileLevel) {
    this.fileLevel = fileLevel;
  }

  public EnvironmentConfigLogSettings fileLocation(Boolean fileLocation) {
    this.fileLocation = fileLocation;
    return this;
  }

   /**
   * Get fileLocation
   * @return fileLocation
  **/
  public Boolean isFileLocation() {
    return fileLocation;
  }

  public void setFileLocation(Boolean fileLocation) {
    this.fileLocation = fileLocation;
  }

  public EnvironmentConfigLogSettings enableWebhookDebugging(Boolean enableWebhookDebugging) {
    this.enableWebhookDebugging = enableWebhookDebugging;
    return this;
  }

   /**
   * Get enableWebhookDebugging
   * @return enableWebhookDebugging
  **/
  public Boolean isEnableWebhookDebugging() {
    return enableWebhookDebugging;
  }

  public void setEnableWebhookDebugging(Boolean enableWebhookDebugging) {
    this.enableWebhookDebugging = enableWebhookDebugging;
  }

  public EnvironmentConfigLogSettings enableDiagnostics(Boolean enableDiagnostics) {
    this.enableDiagnostics = enableDiagnostics;
    return this;
  }

   /**
   * Get enableDiagnostics
   * @return enableDiagnostics
  **/
  public Boolean isEnableDiagnostics() {
    return enableDiagnostics;
  }

  public void setEnableDiagnostics(Boolean enableDiagnostics) {
    this.enableDiagnostics = enableDiagnostics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentConfigLogSettings environmentConfigLogSettings = (EnvironmentConfigLogSettings) o;
    return Objects.equals(this.enableConsole, environmentConfigLogSettings.enableConsole) &&
        Objects.equals(this.consoleLevel, environmentConfigLogSettings.consoleLevel) &&
        Objects.equals(this.enableFile, environmentConfigLogSettings.enableFile) &&
        Objects.equals(this.fileLevel, environmentConfigLogSettings.fileLevel) &&
        Objects.equals(this.fileLocation, environmentConfigLogSettings.fileLocation) &&
        Objects.equals(this.enableWebhookDebugging, environmentConfigLogSettings.enableWebhookDebugging) &&
        Objects.equals(this.enableDiagnostics, environmentConfigLogSettings.enableDiagnostics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableConsole, consoleLevel, enableFile, fileLevel, fileLocation, enableWebhookDebugging, enableDiagnostics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentConfigLogSettings {\n");
    
    sb.append("    enableConsole: ").append(toIndentedString(enableConsole)).append("\n");
    sb.append("    consoleLevel: ").append(toIndentedString(consoleLevel)).append("\n");
    sb.append("    enableFile: ").append(toIndentedString(enableFile)).append("\n");
    sb.append("    fileLevel: ").append(toIndentedString(fileLevel)).append("\n");
    sb.append("    fileLocation: ").append(toIndentedString(fileLocation)).append("\n");
    sb.append("    enableWebhookDebugging: ").append(toIndentedString(enableWebhookDebugging)).append("\n");
    sb.append("    enableDiagnostics: ").append(toIndentedString(enableDiagnostics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
