/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnvironmentConfigSupportSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class EnvironmentConfigSupportSettings {
  @JsonProperty("TermsOfServiceLink")
  private Boolean termsOfServiceLink = null;

  @JsonProperty("PrivacyPolicyLink")
  private Boolean privacyPolicyLink = null;

  @JsonProperty("AboutLink")
  private Boolean aboutLink = null;

  @JsonProperty("HelpLink")
  private Boolean helpLink = null;

  @JsonProperty("ReportAProblemLink")
  private Boolean reportAProblemLink = null;

  @JsonProperty("SupportEmail")
  private Boolean supportEmail = null;

  public EnvironmentConfigSupportSettings termsOfServiceLink(Boolean termsOfServiceLink) {
    this.termsOfServiceLink = termsOfServiceLink;
    return this;
  }

   /**
   * Get termsOfServiceLink
   * @return termsOfServiceLink
  **/
  public Boolean isTermsOfServiceLink() {
    return termsOfServiceLink;
  }

  public void setTermsOfServiceLink(Boolean termsOfServiceLink) {
    this.termsOfServiceLink = termsOfServiceLink;
  }

  public EnvironmentConfigSupportSettings privacyPolicyLink(Boolean privacyPolicyLink) {
    this.privacyPolicyLink = privacyPolicyLink;
    return this;
  }

   /**
   * Get privacyPolicyLink
   * @return privacyPolicyLink
  **/
  public Boolean isPrivacyPolicyLink() {
    return privacyPolicyLink;
  }

  public void setPrivacyPolicyLink(Boolean privacyPolicyLink) {
    this.privacyPolicyLink = privacyPolicyLink;
  }

  public EnvironmentConfigSupportSettings aboutLink(Boolean aboutLink) {
    this.aboutLink = aboutLink;
    return this;
  }

   /**
   * Get aboutLink
   * @return aboutLink
  **/
  public Boolean isAboutLink() {
    return aboutLink;
  }

  public void setAboutLink(Boolean aboutLink) {
    this.aboutLink = aboutLink;
  }

  public EnvironmentConfigSupportSettings helpLink(Boolean helpLink) {
    this.helpLink = helpLink;
    return this;
  }

   /**
   * Get helpLink
   * @return helpLink
  **/
  public Boolean isHelpLink() {
    return helpLink;
  }

  public void setHelpLink(Boolean helpLink) {
    this.helpLink = helpLink;
  }

  public EnvironmentConfigSupportSettings reportAProblemLink(Boolean reportAProblemLink) {
    this.reportAProblemLink = reportAProblemLink;
    return this;
  }

   /**
   * Get reportAProblemLink
   * @return reportAProblemLink
  **/
  public Boolean isReportAProblemLink() {
    return reportAProblemLink;
  }

  public void setReportAProblemLink(Boolean reportAProblemLink) {
    this.reportAProblemLink = reportAProblemLink;
  }

  public EnvironmentConfigSupportSettings supportEmail(Boolean supportEmail) {
    this.supportEmail = supportEmail;
    return this;
  }

   /**
   * Get supportEmail
   * @return supportEmail
  **/
  public Boolean isSupportEmail() {
    return supportEmail;
  }

  public void setSupportEmail(Boolean supportEmail) {
    this.supportEmail = supportEmail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentConfigSupportSettings environmentConfigSupportSettings = (EnvironmentConfigSupportSettings) o;
    return Objects.equals(this.termsOfServiceLink, environmentConfigSupportSettings.termsOfServiceLink) &&
        Objects.equals(this.privacyPolicyLink, environmentConfigSupportSettings.privacyPolicyLink) &&
        Objects.equals(this.aboutLink, environmentConfigSupportSettings.aboutLink) &&
        Objects.equals(this.helpLink, environmentConfigSupportSettings.helpLink) &&
        Objects.equals(this.reportAProblemLink, environmentConfigSupportSettings.reportAProblemLink) &&
        Objects.equals(this.supportEmail, environmentConfigSupportSettings.supportEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(termsOfServiceLink, privacyPolicyLink, aboutLink, helpLink, reportAProblemLink, supportEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentConfigSupportSettings {\n");
    
    sb.append("    termsOfServiceLink: ").append(toIndentedString(termsOfServiceLink)).append("\n");
    sb.append("    privacyPolicyLink: ").append(toIndentedString(privacyPolicyLink)).append("\n");
    sb.append("    aboutLink: ").append(toIndentedString(aboutLink)).append("\n");
    sb.append("    helpLink: ").append(toIndentedString(helpLink)).append("\n");
    sb.append("    reportAProblemLink: ").append(toIndentedString(reportAProblemLink)).append("\n");
    sb.append("    supportEmail: ").append(toIndentedString(supportEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
