/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnvironmentConfigTeamSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class EnvironmentConfigTeamSettings {
  @JsonProperty("SiteName")
  private Boolean siteName = null;

  @JsonProperty("MaxUsersPerTeam")
  private Boolean maxUsersPerTeam = null;

  @JsonProperty("EnableTeamCreation")
  private Boolean enableTeamCreation = null;

  @JsonProperty("EnableUserCreation")
  private Boolean enableUserCreation = null;

  @JsonProperty("EnableOpenServer")
  private Boolean enableOpenServer = null;

  @JsonProperty("RestrictCreationToDomains")
  private Boolean restrictCreationToDomains = null;

  @JsonProperty("EnableCustomBrand")
  private Boolean enableCustomBrand = null;

  @JsonProperty("CustomBrandText")
  private Boolean customBrandText = null;

  @JsonProperty("CustomDescriptionText")
  private Boolean customDescriptionText = null;

  @JsonProperty("RestrictDirectMessage")
  private Boolean restrictDirectMessage = null;

  @JsonProperty("RestrictTeamInvite")
  private Boolean restrictTeamInvite = null;

  @JsonProperty("RestrictPublicChannelManagement")
  private Boolean restrictPublicChannelManagement = null;

  @JsonProperty("RestrictPrivateChannelManagement")
  private Boolean restrictPrivateChannelManagement = null;

  @JsonProperty("RestrictPublicChannelCreation")
  private Boolean restrictPublicChannelCreation = null;

  @JsonProperty("RestrictPrivateChannelCreation")
  private Boolean restrictPrivateChannelCreation = null;

  @JsonProperty("RestrictPublicChannelDeletion")
  private Boolean restrictPublicChannelDeletion = null;

  @JsonProperty("RestrictPrivateChannelDeletion")
  private Boolean restrictPrivateChannelDeletion = null;

  @JsonProperty("UserStatusAwayTimeout")
  private Boolean userStatusAwayTimeout = null;

  @JsonProperty("MaxChannelsPerTeam")
  private Boolean maxChannelsPerTeam = null;

  @JsonProperty("MaxNotificationsPerChannel")
  private Boolean maxNotificationsPerChannel = null;

  public EnvironmentConfigTeamSettings siteName(Boolean siteName) {
    this.siteName = siteName;
    return this;
  }

   /**
   * Get siteName
   * @return siteName
  **/
  public Boolean isSiteName() {
    return siteName;
  }

  public void setSiteName(Boolean siteName) {
    this.siteName = siteName;
  }

  public EnvironmentConfigTeamSettings maxUsersPerTeam(Boolean maxUsersPerTeam) {
    this.maxUsersPerTeam = maxUsersPerTeam;
    return this;
  }

   /**
   * Get maxUsersPerTeam
   * @return maxUsersPerTeam
  **/
  public Boolean isMaxUsersPerTeam() {
    return maxUsersPerTeam;
  }

  public void setMaxUsersPerTeam(Boolean maxUsersPerTeam) {
    this.maxUsersPerTeam = maxUsersPerTeam;
  }

  public EnvironmentConfigTeamSettings enableTeamCreation(Boolean enableTeamCreation) {
    this.enableTeamCreation = enableTeamCreation;
    return this;
  }

   /**
   * Get enableTeamCreation
   * @return enableTeamCreation
  **/
  public Boolean isEnableTeamCreation() {
    return enableTeamCreation;
  }

  public void setEnableTeamCreation(Boolean enableTeamCreation) {
    this.enableTeamCreation = enableTeamCreation;
  }

  public EnvironmentConfigTeamSettings enableUserCreation(Boolean enableUserCreation) {
    this.enableUserCreation = enableUserCreation;
    return this;
  }

   /**
   * Get enableUserCreation
   * @return enableUserCreation
  **/
  public Boolean isEnableUserCreation() {
    return enableUserCreation;
  }

  public void setEnableUserCreation(Boolean enableUserCreation) {
    this.enableUserCreation = enableUserCreation;
  }

  public EnvironmentConfigTeamSettings enableOpenServer(Boolean enableOpenServer) {
    this.enableOpenServer = enableOpenServer;
    return this;
  }

   /**
   * Get enableOpenServer
   * @return enableOpenServer
  **/
  public Boolean isEnableOpenServer() {
    return enableOpenServer;
  }

  public void setEnableOpenServer(Boolean enableOpenServer) {
    this.enableOpenServer = enableOpenServer;
  }

  public EnvironmentConfigTeamSettings restrictCreationToDomains(Boolean restrictCreationToDomains) {
    this.restrictCreationToDomains = restrictCreationToDomains;
    return this;
  }

   /**
   * Get restrictCreationToDomains
   * @return restrictCreationToDomains
  **/
  public Boolean isRestrictCreationToDomains() {
    return restrictCreationToDomains;
  }

  public void setRestrictCreationToDomains(Boolean restrictCreationToDomains) {
    this.restrictCreationToDomains = restrictCreationToDomains;
  }

  public EnvironmentConfigTeamSettings enableCustomBrand(Boolean enableCustomBrand) {
    this.enableCustomBrand = enableCustomBrand;
    return this;
  }

   /**
   * Get enableCustomBrand
   * @return enableCustomBrand
  **/
  public Boolean isEnableCustomBrand() {
    return enableCustomBrand;
  }

  public void setEnableCustomBrand(Boolean enableCustomBrand) {
    this.enableCustomBrand = enableCustomBrand;
  }

  public EnvironmentConfigTeamSettings customBrandText(Boolean customBrandText) {
    this.customBrandText = customBrandText;
    return this;
  }

   /**
   * Get customBrandText
   * @return customBrandText
  **/
  public Boolean isCustomBrandText() {
    return customBrandText;
  }

  public void setCustomBrandText(Boolean customBrandText) {
    this.customBrandText = customBrandText;
  }

  public EnvironmentConfigTeamSettings customDescriptionText(Boolean customDescriptionText) {
    this.customDescriptionText = customDescriptionText;
    return this;
  }

   /**
   * Get customDescriptionText
   * @return customDescriptionText
  **/
  public Boolean isCustomDescriptionText() {
    return customDescriptionText;
  }

  public void setCustomDescriptionText(Boolean customDescriptionText) {
    this.customDescriptionText = customDescriptionText;
  }

  public EnvironmentConfigTeamSettings restrictDirectMessage(Boolean restrictDirectMessage) {
    this.restrictDirectMessage = restrictDirectMessage;
    return this;
  }

   /**
   * Get restrictDirectMessage
   * @return restrictDirectMessage
  **/
  public Boolean isRestrictDirectMessage() {
    return restrictDirectMessage;
  }

  public void setRestrictDirectMessage(Boolean restrictDirectMessage) {
    this.restrictDirectMessage = restrictDirectMessage;
  }

  public EnvironmentConfigTeamSettings restrictTeamInvite(Boolean restrictTeamInvite) {
    this.restrictTeamInvite = restrictTeamInvite;
    return this;
  }

   /**
   * Get restrictTeamInvite
   * @return restrictTeamInvite
  **/
  public Boolean isRestrictTeamInvite() {
    return restrictTeamInvite;
  }

  public void setRestrictTeamInvite(Boolean restrictTeamInvite) {
    this.restrictTeamInvite = restrictTeamInvite;
  }

  public EnvironmentConfigTeamSettings restrictPublicChannelManagement(Boolean restrictPublicChannelManagement) {
    this.restrictPublicChannelManagement = restrictPublicChannelManagement;
    return this;
  }

   /**
   * Get restrictPublicChannelManagement
   * @return restrictPublicChannelManagement
  **/
  public Boolean isRestrictPublicChannelManagement() {
    return restrictPublicChannelManagement;
  }

  public void setRestrictPublicChannelManagement(Boolean restrictPublicChannelManagement) {
    this.restrictPublicChannelManagement = restrictPublicChannelManagement;
  }

  public EnvironmentConfigTeamSettings restrictPrivateChannelManagement(Boolean restrictPrivateChannelManagement) {
    this.restrictPrivateChannelManagement = restrictPrivateChannelManagement;
    return this;
  }

   /**
   * Get restrictPrivateChannelManagement
   * @return restrictPrivateChannelManagement
  **/
  public Boolean isRestrictPrivateChannelManagement() {
    return restrictPrivateChannelManagement;
  }

  public void setRestrictPrivateChannelManagement(Boolean restrictPrivateChannelManagement) {
    this.restrictPrivateChannelManagement = restrictPrivateChannelManagement;
  }

  public EnvironmentConfigTeamSettings restrictPublicChannelCreation(Boolean restrictPublicChannelCreation) {
    this.restrictPublicChannelCreation = restrictPublicChannelCreation;
    return this;
  }

   /**
   * Get restrictPublicChannelCreation
   * @return restrictPublicChannelCreation
  **/
  public Boolean isRestrictPublicChannelCreation() {
    return restrictPublicChannelCreation;
  }

  public void setRestrictPublicChannelCreation(Boolean restrictPublicChannelCreation) {
    this.restrictPublicChannelCreation = restrictPublicChannelCreation;
  }

  public EnvironmentConfigTeamSettings restrictPrivateChannelCreation(Boolean restrictPrivateChannelCreation) {
    this.restrictPrivateChannelCreation = restrictPrivateChannelCreation;
    return this;
  }

   /**
   * Get restrictPrivateChannelCreation
   * @return restrictPrivateChannelCreation
  **/
  public Boolean isRestrictPrivateChannelCreation() {
    return restrictPrivateChannelCreation;
  }

  public void setRestrictPrivateChannelCreation(Boolean restrictPrivateChannelCreation) {
    this.restrictPrivateChannelCreation = restrictPrivateChannelCreation;
  }

  public EnvironmentConfigTeamSettings restrictPublicChannelDeletion(Boolean restrictPublicChannelDeletion) {
    this.restrictPublicChannelDeletion = restrictPublicChannelDeletion;
    return this;
  }

   /**
   * Get restrictPublicChannelDeletion
   * @return restrictPublicChannelDeletion
  **/
  public Boolean isRestrictPublicChannelDeletion() {
    return restrictPublicChannelDeletion;
  }

  public void setRestrictPublicChannelDeletion(Boolean restrictPublicChannelDeletion) {
    this.restrictPublicChannelDeletion = restrictPublicChannelDeletion;
  }

  public EnvironmentConfigTeamSettings restrictPrivateChannelDeletion(Boolean restrictPrivateChannelDeletion) {
    this.restrictPrivateChannelDeletion = restrictPrivateChannelDeletion;
    return this;
  }

   /**
   * Get restrictPrivateChannelDeletion
   * @return restrictPrivateChannelDeletion
  **/
  public Boolean isRestrictPrivateChannelDeletion() {
    return restrictPrivateChannelDeletion;
  }

  public void setRestrictPrivateChannelDeletion(Boolean restrictPrivateChannelDeletion) {
    this.restrictPrivateChannelDeletion = restrictPrivateChannelDeletion;
  }

  public EnvironmentConfigTeamSettings userStatusAwayTimeout(Boolean userStatusAwayTimeout) {
    this.userStatusAwayTimeout = userStatusAwayTimeout;
    return this;
  }

   /**
   * Get userStatusAwayTimeout
   * @return userStatusAwayTimeout
  **/
  public Boolean isUserStatusAwayTimeout() {
    return userStatusAwayTimeout;
  }

  public void setUserStatusAwayTimeout(Boolean userStatusAwayTimeout) {
    this.userStatusAwayTimeout = userStatusAwayTimeout;
  }

  public EnvironmentConfigTeamSettings maxChannelsPerTeam(Boolean maxChannelsPerTeam) {
    this.maxChannelsPerTeam = maxChannelsPerTeam;
    return this;
  }

   /**
   * Get maxChannelsPerTeam
   * @return maxChannelsPerTeam
  **/
  public Boolean isMaxChannelsPerTeam() {
    return maxChannelsPerTeam;
  }

  public void setMaxChannelsPerTeam(Boolean maxChannelsPerTeam) {
    this.maxChannelsPerTeam = maxChannelsPerTeam;
  }

  public EnvironmentConfigTeamSettings maxNotificationsPerChannel(Boolean maxNotificationsPerChannel) {
    this.maxNotificationsPerChannel = maxNotificationsPerChannel;
    return this;
  }

   /**
   * Get maxNotificationsPerChannel
   * @return maxNotificationsPerChannel
  **/
  public Boolean isMaxNotificationsPerChannel() {
    return maxNotificationsPerChannel;
  }

  public void setMaxNotificationsPerChannel(Boolean maxNotificationsPerChannel) {
    this.maxNotificationsPerChannel = maxNotificationsPerChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentConfigTeamSettings environmentConfigTeamSettings = (EnvironmentConfigTeamSettings) o;
    return Objects.equals(this.siteName, environmentConfigTeamSettings.siteName) &&
        Objects.equals(this.maxUsersPerTeam, environmentConfigTeamSettings.maxUsersPerTeam) &&
        Objects.equals(this.enableTeamCreation, environmentConfigTeamSettings.enableTeamCreation) &&
        Objects.equals(this.enableUserCreation, environmentConfigTeamSettings.enableUserCreation) &&
        Objects.equals(this.enableOpenServer, environmentConfigTeamSettings.enableOpenServer) &&
        Objects.equals(this.restrictCreationToDomains, environmentConfigTeamSettings.restrictCreationToDomains) &&
        Objects.equals(this.enableCustomBrand, environmentConfigTeamSettings.enableCustomBrand) &&
        Objects.equals(this.customBrandText, environmentConfigTeamSettings.customBrandText) &&
        Objects.equals(this.customDescriptionText, environmentConfigTeamSettings.customDescriptionText) &&
        Objects.equals(this.restrictDirectMessage, environmentConfigTeamSettings.restrictDirectMessage) &&
        Objects.equals(this.restrictTeamInvite, environmentConfigTeamSettings.restrictTeamInvite) &&
        Objects.equals(this.restrictPublicChannelManagement, environmentConfigTeamSettings.restrictPublicChannelManagement) &&
        Objects.equals(this.restrictPrivateChannelManagement, environmentConfigTeamSettings.restrictPrivateChannelManagement) &&
        Objects.equals(this.restrictPublicChannelCreation, environmentConfigTeamSettings.restrictPublicChannelCreation) &&
        Objects.equals(this.restrictPrivateChannelCreation, environmentConfigTeamSettings.restrictPrivateChannelCreation) &&
        Objects.equals(this.restrictPublicChannelDeletion, environmentConfigTeamSettings.restrictPublicChannelDeletion) &&
        Objects.equals(this.restrictPrivateChannelDeletion, environmentConfigTeamSettings.restrictPrivateChannelDeletion) &&
        Objects.equals(this.userStatusAwayTimeout, environmentConfigTeamSettings.userStatusAwayTimeout) &&
        Objects.equals(this.maxChannelsPerTeam, environmentConfigTeamSettings.maxChannelsPerTeam) &&
        Objects.equals(this.maxNotificationsPerChannel, environmentConfigTeamSettings.maxNotificationsPerChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(siteName, maxUsersPerTeam, enableTeamCreation, enableUserCreation, enableOpenServer, restrictCreationToDomains, enableCustomBrand, customBrandText, customDescriptionText, restrictDirectMessage, restrictTeamInvite, restrictPublicChannelManagement, restrictPrivateChannelManagement, restrictPublicChannelCreation, restrictPrivateChannelCreation, restrictPublicChannelDeletion, restrictPrivateChannelDeletion, userStatusAwayTimeout, maxChannelsPerTeam, maxNotificationsPerChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentConfigTeamSettings {\n");
    
    sb.append("    siteName: ").append(toIndentedString(siteName)).append("\n");
    sb.append("    maxUsersPerTeam: ").append(toIndentedString(maxUsersPerTeam)).append("\n");
    sb.append("    enableTeamCreation: ").append(toIndentedString(enableTeamCreation)).append("\n");
    sb.append("    enableUserCreation: ").append(toIndentedString(enableUserCreation)).append("\n");
    sb.append("    enableOpenServer: ").append(toIndentedString(enableOpenServer)).append("\n");
    sb.append("    restrictCreationToDomains: ").append(toIndentedString(restrictCreationToDomains)).append("\n");
    sb.append("    enableCustomBrand: ").append(toIndentedString(enableCustomBrand)).append("\n");
    sb.append("    customBrandText: ").append(toIndentedString(customBrandText)).append("\n");
    sb.append("    customDescriptionText: ").append(toIndentedString(customDescriptionText)).append("\n");
    sb.append("    restrictDirectMessage: ").append(toIndentedString(restrictDirectMessage)).append("\n");
    sb.append("    restrictTeamInvite: ").append(toIndentedString(restrictTeamInvite)).append("\n");
    sb.append("    restrictPublicChannelManagement: ").append(toIndentedString(restrictPublicChannelManagement)).append("\n");
    sb.append("    restrictPrivateChannelManagement: ").append(toIndentedString(restrictPrivateChannelManagement)).append("\n");
    sb.append("    restrictPublicChannelCreation: ").append(toIndentedString(restrictPublicChannelCreation)).append("\n");
    sb.append("    restrictPrivateChannelCreation: ").append(toIndentedString(restrictPrivateChannelCreation)).append("\n");
    sb.append("    restrictPublicChannelDeletion: ").append(toIndentedString(restrictPublicChannelDeletion)).append("\n");
    sb.append("    restrictPrivateChannelDeletion: ").append(toIndentedString(restrictPrivateChannelDeletion)).append("\n");
    sb.append("    userStatusAwayTimeout: ").append(toIndentedString(userStatusAwayTimeout)).append("\n");
    sb.append("    maxChannelsPerTeam: ").append(toIndentedString(maxChannelsPerTeam)).append("\n");
    sb.append("    maxNotificationsPerChannel: ").append(toIndentedString(maxNotificationsPerChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
