/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnvironmentConfigRateLimitSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class EnvironmentConfigRateLimitSettings {
  @JsonProperty("Enable")
  private Boolean enable = null;

  @JsonProperty("PerSec")
  private Boolean perSec = null;

  @JsonProperty("MaxBurst")
  private Boolean maxBurst = null;

  @JsonProperty("MemoryStoreSize")
  private Boolean memoryStoreSize = null;

  @JsonProperty("VaryByRemoteAddr")
  private Boolean varyByRemoteAddr = null;

  @JsonProperty("VaryByHeader")
  private Boolean varyByHeader = null;

  public EnvironmentConfigRateLimitSettings enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public EnvironmentConfigRateLimitSettings perSec(Boolean perSec) {
    this.perSec = perSec;
    return this;
  }

   /**
   * Get perSec
   * @return perSec
  **/
  public Boolean isPerSec() {
    return perSec;
  }

  public void setPerSec(Boolean perSec) {
    this.perSec = perSec;
  }

  public EnvironmentConfigRateLimitSettings maxBurst(Boolean maxBurst) {
    this.maxBurst = maxBurst;
    return this;
  }

   /**
   * Get maxBurst
   * @return maxBurst
  **/
  public Boolean isMaxBurst() {
    return maxBurst;
  }

  public void setMaxBurst(Boolean maxBurst) {
    this.maxBurst = maxBurst;
  }

  public EnvironmentConfigRateLimitSettings memoryStoreSize(Boolean memoryStoreSize) {
    this.memoryStoreSize = memoryStoreSize;
    return this;
  }

   /**
   * Get memoryStoreSize
   * @return memoryStoreSize
  **/
  public Boolean isMemoryStoreSize() {
    return memoryStoreSize;
  }

  public void setMemoryStoreSize(Boolean memoryStoreSize) {
    this.memoryStoreSize = memoryStoreSize;
  }

  public EnvironmentConfigRateLimitSettings varyByRemoteAddr(Boolean varyByRemoteAddr) {
    this.varyByRemoteAddr = varyByRemoteAddr;
    return this;
  }

   /**
   * Get varyByRemoteAddr
   * @return varyByRemoteAddr
  **/
  public Boolean isVaryByRemoteAddr() {
    return varyByRemoteAddr;
  }

  public void setVaryByRemoteAddr(Boolean varyByRemoteAddr) {
    this.varyByRemoteAddr = varyByRemoteAddr;
  }

  public EnvironmentConfigRateLimitSettings varyByHeader(Boolean varyByHeader) {
    this.varyByHeader = varyByHeader;
    return this;
  }

   /**
   * Get varyByHeader
   * @return varyByHeader
  **/
  public Boolean isVaryByHeader() {
    return varyByHeader;
  }

  public void setVaryByHeader(Boolean varyByHeader) {
    this.varyByHeader = varyByHeader;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentConfigRateLimitSettings environmentConfigRateLimitSettings = (EnvironmentConfigRateLimitSettings) o;
    return Objects.equals(this.enable, environmentConfigRateLimitSettings.enable) &&
        Objects.equals(this.perSec, environmentConfigRateLimitSettings.perSec) &&
        Objects.equals(this.maxBurst, environmentConfigRateLimitSettings.maxBurst) &&
        Objects.equals(this.memoryStoreSize, environmentConfigRateLimitSettings.memoryStoreSize) &&
        Objects.equals(this.varyByRemoteAddr, environmentConfigRateLimitSettings.varyByRemoteAddr) &&
        Objects.equals(this.varyByHeader, environmentConfigRateLimitSettings.varyByHeader);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, perSec, maxBurst, memoryStoreSize, varyByRemoteAddr, varyByHeader);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentConfigRateLimitSettings {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    perSec: ").append(toIndentedString(perSec)).append("\n");
    sb.append("    maxBurst: ").append(toIndentedString(maxBurst)).append("\n");
    sb.append("    memoryStoreSize: ").append(toIndentedString(memoryStoreSize)).append("\n");
    sb.append("    varyByRemoteAddr: ").append(toIndentedString(varyByRemoteAddr)).append("\n");
    sb.append("    varyByHeader: ").append(toIndentedString(varyByHeader)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
