/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnvironmentConfigEmailSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class EnvironmentConfigEmailSettings {
  @JsonProperty("EnableSignUpWithEmail")
  private Boolean enableSignUpWithEmail = null;

  @JsonProperty("EnableSignInWithEmail")
  private Boolean enableSignInWithEmail = null;

  @JsonProperty("EnableSignInWithUsername")
  private Boolean enableSignInWithUsername = null;

  @JsonProperty("SendEmailNotifications")
  private Boolean sendEmailNotifications = null;

  @JsonProperty("RequireEmailVerification")
  private Boolean requireEmailVerification = null;

  @JsonProperty("FeedbackName")
  private Boolean feedbackName = null;

  @JsonProperty("FeedbackEmail")
  private Boolean feedbackEmail = null;

  @JsonProperty("FeedbackOrganization")
  private Boolean feedbackOrganization = null;

  @JsonProperty("SMTPUsername")
  private Boolean smTPUsername = null;

  @JsonProperty("SMTPPassword")
  private Boolean smTPPassword = null;

  @JsonProperty("SMTPServer")
  private Boolean smTPServer = null;

  @JsonProperty("SMTPPort")
  private Boolean smTPPort = null;

  @JsonProperty("ConnectionSecurity")
  private Boolean connectionSecurity = null;

  @JsonProperty("InviteSalt")
  private Boolean inviteSalt = null;

  @JsonProperty("PasswordResetSalt")
  private Boolean passwordResetSalt = null;

  @JsonProperty("SendPushNotifications")
  private Boolean sendPushNotifications = null;

  @JsonProperty("PushNotificationServer")
  private Boolean pushNotificationServer = null;

  @JsonProperty("PushNotificationContents")
  private Boolean pushNotificationContents = null;

  @JsonProperty("EnableEmailBatching")
  private Boolean enableEmailBatching = null;

  @JsonProperty("EmailBatchingBufferSize")
  private Boolean emailBatchingBufferSize = null;

  @JsonProperty("EmailBatchingInterval")
  private Boolean emailBatchingInterval = null;

  public EnvironmentConfigEmailSettings enableSignUpWithEmail(Boolean enableSignUpWithEmail) {
    this.enableSignUpWithEmail = enableSignUpWithEmail;
    return this;
  }

   /**
   * Get enableSignUpWithEmail
   * @return enableSignUpWithEmail
  **/
  public Boolean isEnableSignUpWithEmail() {
    return enableSignUpWithEmail;
  }

  public void setEnableSignUpWithEmail(Boolean enableSignUpWithEmail) {
    this.enableSignUpWithEmail = enableSignUpWithEmail;
  }

  public EnvironmentConfigEmailSettings enableSignInWithEmail(Boolean enableSignInWithEmail) {
    this.enableSignInWithEmail = enableSignInWithEmail;
    return this;
  }

   /**
   * Get enableSignInWithEmail
   * @return enableSignInWithEmail
  **/
  public Boolean isEnableSignInWithEmail() {
    return enableSignInWithEmail;
  }

  public void setEnableSignInWithEmail(Boolean enableSignInWithEmail) {
    this.enableSignInWithEmail = enableSignInWithEmail;
  }

  public EnvironmentConfigEmailSettings enableSignInWithUsername(Boolean enableSignInWithUsername) {
    this.enableSignInWithUsername = enableSignInWithUsername;
    return this;
  }

   /**
   * Get enableSignInWithUsername
   * @return enableSignInWithUsername
  **/
  public Boolean isEnableSignInWithUsername() {
    return enableSignInWithUsername;
  }

  public void setEnableSignInWithUsername(Boolean enableSignInWithUsername) {
    this.enableSignInWithUsername = enableSignInWithUsername;
  }

  public EnvironmentConfigEmailSettings sendEmailNotifications(Boolean sendEmailNotifications) {
    this.sendEmailNotifications = sendEmailNotifications;
    return this;
  }

   /**
   * Get sendEmailNotifications
   * @return sendEmailNotifications
  **/
  public Boolean isSendEmailNotifications() {
    return sendEmailNotifications;
  }

  public void setSendEmailNotifications(Boolean sendEmailNotifications) {
    this.sendEmailNotifications = sendEmailNotifications;
  }

  public EnvironmentConfigEmailSettings requireEmailVerification(Boolean requireEmailVerification) {
    this.requireEmailVerification = requireEmailVerification;
    return this;
  }

   /**
   * Get requireEmailVerification
   * @return requireEmailVerification
  **/
  public Boolean isRequireEmailVerification() {
    return requireEmailVerification;
  }

  public void setRequireEmailVerification(Boolean requireEmailVerification) {
    this.requireEmailVerification = requireEmailVerification;
  }

  public EnvironmentConfigEmailSettings feedbackName(Boolean feedbackName) {
    this.feedbackName = feedbackName;
    return this;
  }

   /**
   * Get feedbackName
   * @return feedbackName
  **/
  public Boolean isFeedbackName() {
    return feedbackName;
  }

  public void setFeedbackName(Boolean feedbackName) {
    this.feedbackName = feedbackName;
  }

  public EnvironmentConfigEmailSettings feedbackEmail(Boolean feedbackEmail) {
    this.feedbackEmail = feedbackEmail;
    return this;
  }

   /**
   * Get feedbackEmail
   * @return feedbackEmail
  **/
  public Boolean isFeedbackEmail() {
    return feedbackEmail;
  }

  public void setFeedbackEmail(Boolean feedbackEmail) {
    this.feedbackEmail = feedbackEmail;
  }

  public EnvironmentConfigEmailSettings feedbackOrganization(Boolean feedbackOrganization) {
    this.feedbackOrganization = feedbackOrganization;
    return this;
  }

   /**
   * Get feedbackOrganization
   * @return feedbackOrganization
  **/
  public Boolean isFeedbackOrganization() {
    return feedbackOrganization;
  }

  public void setFeedbackOrganization(Boolean feedbackOrganization) {
    this.feedbackOrganization = feedbackOrganization;
  }

  public EnvironmentConfigEmailSettings smTPUsername(Boolean smTPUsername) {
    this.smTPUsername = smTPUsername;
    return this;
  }

   /**
   * Get smTPUsername
   * @return smTPUsername
  **/
  public Boolean isSmTPUsername() {
    return smTPUsername;
  }

  public void setSmTPUsername(Boolean smTPUsername) {
    this.smTPUsername = smTPUsername;
  }

  public EnvironmentConfigEmailSettings smTPPassword(Boolean smTPPassword) {
    this.smTPPassword = smTPPassword;
    return this;
  }

   /**
   * Get smTPPassword
   * @return smTPPassword
  **/
  public Boolean isSmTPPassword() {
    return smTPPassword;
  }

  public void setSmTPPassword(Boolean smTPPassword) {
    this.smTPPassword = smTPPassword;
  }

  public EnvironmentConfigEmailSettings smTPServer(Boolean smTPServer) {
    this.smTPServer = smTPServer;
    return this;
  }

   /**
   * Get smTPServer
   * @return smTPServer
  **/
  public Boolean isSmTPServer() {
    return smTPServer;
  }

  public void setSmTPServer(Boolean smTPServer) {
    this.smTPServer = smTPServer;
  }

  public EnvironmentConfigEmailSettings smTPPort(Boolean smTPPort) {
    this.smTPPort = smTPPort;
    return this;
  }

   /**
   * Get smTPPort
   * @return smTPPort
  **/
  public Boolean isSmTPPort() {
    return smTPPort;
  }

  public void setSmTPPort(Boolean smTPPort) {
    this.smTPPort = smTPPort;
  }

  public EnvironmentConfigEmailSettings connectionSecurity(Boolean connectionSecurity) {
    this.connectionSecurity = connectionSecurity;
    return this;
  }

   /**
   * Get connectionSecurity
   * @return connectionSecurity
  **/
  public Boolean isConnectionSecurity() {
    return connectionSecurity;
  }

  public void setConnectionSecurity(Boolean connectionSecurity) {
    this.connectionSecurity = connectionSecurity;
  }

  public EnvironmentConfigEmailSettings inviteSalt(Boolean inviteSalt) {
    this.inviteSalt = inviteSalt;
    return this;
  }

   /**
   * Get inviteSalt
   * @return inviteSalt
  **/
  public Boolean isInviteSalt() {
    return inviteSalt;
  }

  public void setInviteSalt(Boolean inviteSalt) {
    this.inviteSalt = inviteSalt;
  }

  public EnvironmentConfigEmailSettings passwordResetSalt(Boolean passwordResetSalt) {
    this.passwordResetSalt = passwordResetSalt;
    return this;
  }

   /**
   * Get passwordResetSalt
   * @return passwordResetSalt
  **/
  public Boolean isPasswordResetSalt() {
    return passwordResetSalt;
  }

  public void setPasswordResetSalt(Boolean passwordResetSalt) {
    this.passwordResetSalt = passwordResetSalt;
  }

  public EnvironmentConfigEmailSettings sendPushNotifications(Boolean sendPushNotifications) {
    this.sendPushNotifications = sendPushNotifications;
    return this;
  }

   /**
   * Get sendPushNotifications
   * @return sendPushNotifications
  **/
  public Boolean isSendPushNotifications() {
    return sendPushNotifications;
  }

  public void setSendPushNotifications(Boolean sendPushNotifications) {
    this.sendPushNotifications = sendPushNotifications;
  }

  public EnvironmentConfigEmailSettings pushNotificationServer(Boolean pushNotificationServer) {
    this.pushNotificationServer = pushNotificationServer;
    return this;
  }

   /**
   * Get pushNotificationServer
   * @return pushNotificationServer
  **/
  public Boolean isPushNotificationServer() {
    return pushNotificationServer;
  }

  public void setPushNotificationServer(Boolean pushNotificationServer) {
    this.pushNotificationServer = pushNotificationServer;
  }

  public EnvironmentConfigEmailSettings pushNotificationContents(Boolean pushNotificationContents) {
    this.pushNotificationContents = pushNotificationContents;
    return this;
  }

   /**
   * Get pushNotificationContents
   * @return pushNotificationContents
  **/
  public Boolean isPushNotificationContents() {
    return pushNotificationContents;
  }

  public void setPushNotificationContents(Boolean pushNotificationContents) {
    this.pushNotificationContents = pushNotificationContents;
  }

  public EnvironmentConfigEmailSettings enableEmailBatching(Boolean enableEmailBatching) {
    this.enableEmailBatching = enableEmailBatching;
    return this;
  }

   /**
   * Get enableEmailBatching
   * @return enableEmailBatching
  **/
  public Boolean isEnableEmailBatching() {
    return enableEmailBatching;
  }

  public void setEnableEmailBatching(Boolean enableEmailBatching) {
    this.enableEmailBatching = enableEmailBatching;
  }

  public EnvironmentConfigEmailSettings emailBatchingBufferSize(Boolean emailBatchingBufferSize) {
    this.emailBatchingBufferSize = emailBatchingBufferSize;
    return this;
  }

   /**
   * Get emailBatchingBufferSize
   * @return emailBatchingBufferSize
  **/
  public Boolean isEmailBatchingBufferSize() {
    return emailBatchingBufferSize;
  }

  public void setEmailBatchingBufferSize(Boolean emailBatchingBufferSize) {
    this.emailBatchingBufferSize = emailBatchingBufferSize;
  }

  public EnvironmentConfigEmailSettings emailBatchingInterval(Boolean emailBatchingInterval) {
    this.emailBatchingInterval = emailBatchingInterval;
    return this;
  }

   /**
   * Get emailBatchingInterval
   * @return emailBatchingInterval
  **/
  public Boolean isEmailBatchingInterval() {
    return emailBatchingInterval;
  }

  public void setEmailBatchingInterval(Boolean emailBatchingInterval) {
    this.emailBatchingInterval = emailBatchingInterval;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentConfigEmailSettings environmentConfigEmailSettings = (EnvironmentConfigEmailSettings) o;
    return Objects.equals(this.enableSignUpWithEmail, environmentConfigEmailSettings.enableSignUpWithEmail) &&
        Objects.equals(this.enableSignInWithEmail, environmentConfigEmailSettings.enableSignInWithEmail) &&
        Objects.equals(this.enableSignInWithUsername, environmentConfigEmailSettings.enableSignInWithUsername) &&
        Objects.equals(this.sendEmailNotifications, environmentConfigEmailSettings.sendEmailNotifications) &&
        Objects.equals(this.requireEmailVerification, environmentConfigEmailSettings.requireEmailVerification) &&
        Objects.equals(this.feedbackName, environmentConfigEmailSettings.feedbackName) &&
        Objects.equals(this.feedbackEmail, environmentConfigEmailSettings.feedbackEmail) &&
        Objects.equals(this.feedbackOrganization, environmentConfigEmailSettings.feedbackOrganization) &&
        Objects.equals(this.smTPUsername, environmentConfigEmailSettings.smTPUsername) &&
        Objects.equals(this.smTPPassword, environmentConfigEmailSettings.smTPPassword) &&
        Objects.equals(this.smTPServer, environmentConfigEmailSettings.smTPServer) &&
        Objects.equals(this.smTPPort, environmentConfigEmailSettings.smTPPort) &&
        Objects.equals(this.connectionSecurity, environmentConfigEmailSettings.connectionSecurity) &&
        Objects.equals(this.inviteSalt, environmentConfigEmailSettings.inviteSalt) &&
        Objects.equals(this.passwordResetSalt, environmentConfigEmailSettings.passwordResetSalt) &&
        Objects.equals(this.sendPushNotifications, environmentConfigEmailSettings.sendPushNotifications) &&
        Objects.equals(this.pushNotificationServer, environmentConfigEmailSettings.pushNotificationServer) &&
        Objects.equals(this.pushNotificationContents, environmentConfigEmailSettings.pushNotificationContents) &&
        Objects.equals(this.enableEmailBatching, environmentConfigEmailSettings.enableEmailBatching) &&
        Objects.equals(this.emailBatchingBufferSize, environmentConfigEmailSettings.emailBatchingBufferSize) &&
        Objects.equals(this.emailBatchingInterval, environmentConfigEmailSettings.emailBatchingInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableSignUpWithEmail, enableSignInWithEmail, enableSignInWithUsername, sendEmailNotifications, requireEmailVerification, feedbackName, feedbackEmail, feedbackOrganization, smTPUsername, smTPPassword, smTPServer, smTPPort, connectionSecurity, inviteSalt, passwordResetSalt, sendPushNotifications, pushNotificationServer, pushNotificationContents, enableEmailBatching, emailBatchingBufferSize, emailBatchingInterval);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentConfigEmailSettings {\n");
    
    sb.append("    enableSignUpWithEmail: ").append(toIndentedString(enableSignUpWithEmail)).append("\n");
    sb.append("    enableSignInWithEmail: ").append(toIndentedString(enableSignInWithEmail)).append("\n");
    sb.append("    enableSignInWithUsername: ").append(toIndentedString(enableSignInWithUsername)).append("\n");
    sb.append("    sendEmailNotifications: ").append(toIndentedString(sendEmailNotifications)).append("\n");
    sb.append("    requireEmailVerification: ").append(toIndentedString(requireEmailVerification)).append("\n");
    sb.append("    feedbackName: ").append(toIndentedString(feedbackName)).append("\n");
    sb.append("    feedbackEmail: ").append(toIndentedString(feedbackEmail)).append("\n");
    sb.append("    feedbackOrganization: ").append(toIndentedString(feedbackOrganization)).append("\n");
    sb.append("    smTPUsername: ").append(toIndentedString(smTPUsername)).append("\n");
    sb.append("    smTPPassword: ").append(toIndentedString(smTPPassword)).append("\n");
    sb.append("    smTPServer: ").append(toIndentedString(smTPServer)).append("\n");
    sb.append("    smTPPort: ").append(toIndentedString(smTPPort)).append("\n");
    sb.append("    connectionSecurity: ").append(toIndentedString(connectionSecurity)).append("\n");
    sb.append("    inviteSalt: ").append(toIndentedString(inviteSalt)).append("\n");
    sb.append("    passwordResetSalt: ").append(toIndentedString(passwordResetSalt)).append("\n");
    sb.append("    sendPushNotifications: ").append(toIndentedString(sendPushNotifications)).append("\n");
    sb.append("    pushNotificationServer: ").append(toIndentedString(pushNotificationServer)).append("\n");
    sb.append("    pushNotificationContents: ").append(toIndentedString(pushNotificationContents)).append("\n");
    sb.append("    enableEmailBatching: ").append(toIndentedString(enableEmailBatching)).append("\n");
    sb.append("    emailBatchingBufferSize: ").append(toIndentedString(emailBatchingBufferSize)).append("\n");
    sb.append("    emailBatchingInterval: ").append(toIndentedString(emailBatchingInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
