/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FileInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class FileInfo {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("post_id")
  private String postId = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("update_at")
  private Long updateAt = null;

  @JsonProperty("delete_at")
  private Long deleteAt = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("extension")
  private String extension = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("mime_type")
  private String mimeType = null;

  @JsonProperty("width")
  private Integer width = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("has_preview_image")
  private Boolean hasPreviewImage = null;

  public FileInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for this file
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FileInfo userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the user that uploaded this file
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public FileInfo postId(String postId) {
    this.postId = postId;
    return this;
  }

   /**
   * If this file is attached to a post, the ID of that post
   * @return postId
  **/
  public String getPostId() {
    return postId;
  }

  public void setPostId(String postId) {
    this.postId = postId;
  }

  public FileInfo createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time in milliseconds a file was created
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public FileInfo updateAt(Long updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * The time in milliseconds a file was last updated
   * @return updateAt
  **/
  public Long getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Long updateAt) {
    this.updateAt = updateAt;
  }

  public FileInfo deleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * The time in milliseconds a file was deleted
   * @return deleteAt
  **/
  public Long getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
  }

  public FileInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the file
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FileInfo extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * The extension at the end of the file name
   * @return extension
  **/
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public FileInfo size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * The size of the file in bytes
   * @return size
  **/
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public FileInfo mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * The MIME type of the file
   * @return mimeType
  **/
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public FileInfo width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * If this file is an image, the width of the file
   * @return width
  **/
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public FileInfo height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * If this file is an image, the height of the file
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public FileInfo hasPreviewImage(Boolean hasPreviewImage) {
    this.hasPreviewImage = hasPreviewImage;
    return this;
  }

   /**
   * If this file is an image, whether or not it has a preview-sized version
   * @return hasPreviewImage
  **/
  public Boolean isHasPreviewImage() {
    return hasPreviewImage;
  }

  public void setHasPreviewImage(Boolean hasPreviewImage) {
    this.hasPreviewImage = hasPreviewImage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileInfo fileInfo = (FileInfo) o;
    return Objects.equals(this.id, fileInfo.id) &&
        Objects.equals(this.userId, fileInfo.userId) &&
        Objects.equals(this.postId, fileInfo.postId) &&
        Objects.equals(this.createAt, fileInfo.createAt) &&
        Objects.equals(this.updateAt, fileInfo.updateAt) &&
        Objects.equals(this.deleteAt, fileInfo.deleteAt) &&
        Objects.equals(this.name, fileInfo.name) &&
        Objects.equals(this.extension, fileInfo.extension) &&
        Objects.equals(this.size, fileInfo.size) &&
        Objects.equals(this.mimeType, fileInfo.mimeType) &&
        Objects.equals(this.width, fileInfo.width) &&
        Objects.equals(this.height, fileInfo.height) &&
        Objects.equals(this.hasPreviewImage, fileInfo.hasPreviewImage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, postId, createAt, updateAt, deleteAt, name, extension, size, mimeType, width, height, hasPreviewImage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    hasPreviewImage: ").append(toIndentedString(hasPreviewImage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
