/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.FileInfo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * FileInfoList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class FileInfoList {
  @JsonProperty("order")
  private List<String> order = null;

  @JsonProperty("file_infos")
  private Map<String, FileInfo> fileInfos = null;

  @JsonProperty("next_file_id")
  private String nextFileId = null;

  @JsonProperty("prev_file_id")
  private String prevFileId = null;

  public FileInfoList order(List<String> order) {
    this.order = order;
    return this;
  }

  public FileInfoList addOrderItem(String orderItem) {
    if (this.order == null) {
      this.order = new ArrayList<>();
    }
    this.order.add(orderItem);
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  public List<String> getOrder() {
    return order;
  }

  public void setOrder(List<String> order) {
    this.order = order;
  }

  public FileInfoList fileInfos(Map<String, FileInfo> fileInfos) {
    this.fileInfos = fileInfos;
    return this;
  }

  public FileInfoList putFileInfosItem(String key, FileInfo fileInfosItem) {
    if (this.fileInfos == null) {
      this.fileInfos = new HashMap<>();
    }
    this.fileInfos.put(key, fileInfosItem);
    return this;
  }

   /**
   * Get fileInfos
   * @return fileInfos
  **/
  public Map<String, FileInfo> getFileInfos() {
    return fileInfos;
  }

  public void setFileInfos(Map<String, FileInfo> fileInfos) {
    this.fileInfos = fileInfos;
  }

  public FileInfoList nextFileId(String nextFileId) {
    this.nextFileId = nextFileId;
    return this;
  }

   /**
   * The ID of next file info. Not omitted when empty or not relevant.
   * @return nextFileId
  **/
  public String getNextFileId() {
    return nextFileId;
  }

  public void setNextFileId(String nextFileId) {
    this.nextFileId = nextFileId;
  }

  public FileInfoList prevFileId(String prevFileId) {
    this.prevFileId = prevFileId;
    return this;
  }

   /**
   * The ID of previous file info. Not omitted when empty or not relevant.
   * @return prevFileId
  **/
  public String getPrevFileId() {
    return prevFileId;
  }

  public void setPrevFileId(String prevFileId) {
    this.prevFileId = prevFileId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileInfoList fileInfoList = (FileInfoList) o;
    return Objects.equals(this.order, fileInfoList.order) &&
        Objects.equals(this.fileInfos, fileInfoList.fileInfos) &&
        Objects.equals(this.nextFileId, fileInfoList.nextFileId) &&
        Objects.equals(this.prevFileId, fileInfoList.prevFileId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, fileInfos, nextFileId, prevFileId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileInfoList {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    fileInfos: ").append(toIndentedString(fileInfos)).append("\n");
    sb.append("    nextFileId: ").append(toIndentedString(nextFileId)).append("\n");
    sb.append("    prevFileId: ").append(toIndentedString(prevFileId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
