/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GroupSyncableChannel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class GroupSyncableChannel {
  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("group_id")
  private String groupId = null;

  @JsonProperty("auto_add")
  private Boolean autoAdd = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("delete_at")
  private Long deleteAt = null;

  @JsonProperty("update_at")
  private Long updateAt = null;

  public GroupSyncableChannel channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * Get channelId
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public GroupSyncableChannel groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public GroupSyncableChannel autoAdd(Boolean autoAdd) {
    this.autoAdd = autoAdd;
    return this;
  }

   /**
   * Get autoAdd
   * @return autoAdd
  **/
  public Boolean isAutoAdd() {
    return autoAdd;
  }

  public void setAutoAdd(Boolean autoAdd) {
    this.autoAdd = autoAdd;
  }

  public GroupSyncableChannel createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * Get createAt
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public GroupSyncableChannel deleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * Get deleteAt
   * @return deleteAt
  **/
  public Long getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
  }

  public GroupSyncableChannel updateAt(Long updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * Get updateAt
   * @return updateAt
  **/
  public Long getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Long updateAt) {
    this.updateAt = updateAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupSyncableChannel groupSyncableChannel = (GroupSyncableChannel) o;
    return Objects.equals(this.channelId, groupSyncableChannel.channelId) &&
        Objects.equals(this.groupId, groupSyncableChannel.groupId) &&
        Objects.equals(this.autoAdd, groupSyncableChannel.autoAdd) &&
        Objects.equals(this.createAt, groupSyncableChannel.createAt) &&
        Objects.equals(this.deleteAt, groupSyncableChannel.deleteAt) &&
        Objects.equals(this.updateAt, groupSyncableChannel.updateAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, groupId, autoAdd, createAt, deleteAt, updateAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupSyncableChannel {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    autoAdd: ").append(toIndentedString(autoAdd)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
