/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GroupSyncableChannels
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class GroupSyncableChannels {
  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("channel_display_name")
  private String channelDisplayName = null;

  @JsonProperty("channel_type")
  private String channelType = null;

  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("team_display_name")
  private String teamDisplayName = null;

  @JsonProperty("team_type")
  private String teamType = null;

  @JsonProperty("group_id")
  private String groupId = null;

  @JsonProperty("auto_add")
  private Boolean autoAdd = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("delete_at")
  private Long deleteAt = null;

  @JsonProperty("update_at")
  private Long updateAt = null;

  public GroupSyncableChannels channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * Get channelId
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public GroupSyncableChannels channelDisplayName(String channelDisplayName) {
    this.channelDisplayName = channelDisplayName;
    return this;
  }

   /**
   * Get channelDisplayName
   * @return channelDisplayName
  **/
  public String getChannelDisplayName() {
    return channelDisplayName;
  }

  public void setChannelDisplayName(String channelDisplayName) {
    this.channelDisplayName = channelDisplayName;
  }

  public GroupSyncableChannels channelType(String channelType) {
    this.channelType = channelType;
    return this;
  }

   /**
   * Get channelType
   * @return channelType
  **/
  public String getChannelType() {
    return channelType;
  }

  public void setChannelType(String channelType) {
    this.channelType = channelType;
  }

  public GroupSyncableChannels teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public GroupSyncableChannels teamDisplayName(String teamDisplayName) {
    this.teamDisplayName = teamDisplayName;
    return this;
  }

   /**
   * Get teamDisplayName
   * @return teamDisplayName
  **/
  public String getTeamDisplayName() {
    return teamDisplayName;
  }

  public void setTeamDisplayName(String teamDisplayName) {
    this.teamDisplayName = teamDisplayName;
  }

  public GroupSyncableChannels teamType(String teamType) {
    this.teamType = teamType;
    return this;
  }

   /**
   * Get teamType
   * @return teamType
  **/
  public String getTeamType() {
    return teamType;
  }

  public void setTeamType(String teamType) {
    this.teamType = teamType;
  }

  public GroupSyncableChannels groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public GroupSyncableChannels autoAdd(Boolean autoAdd) {
    this.autoAdd = autoAdd;
    return this;
  }

   /**
   * Get autoAdd
   * @return autoAdd
  **/
  public Boolean isAutoAdd() {
    return autoAdd;
  }

  public void setAutoAdd(Boolean autoAdd) {
    this.autoAdd = autoAdd;
  }

  public GroupSyncableChannels createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * Get createAt
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public GroupSyncableChannels deleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * Get deleteAt
   * @return deleteAt
  **/
  public Long getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
  }

  public GroupSyncableChannels updateAt(Long updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * Get updateAt
   * @return updateAt
  **/
  public Long getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Long updateAt) {
    this.updateAt = updateAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupSyncableChannels groupSyncableChannels = (GroupSyncableChannels) o;
    return Objects.equals(this.channelId, groupSyncableChannels.channelId) &&
        Objects.equals(this.channelDisplayName, groupSyncableChannels.channelDisplayName) &&
        Objects.equals(this.channelType, groupSyncableChannels.channelType) &&
        Objects.equals(this.teamId, groupSyncableChannels.teamId) &&
        Objects.equals(this.teamDisplayName, groupSyncableChannels.teamDisplayName) &&
        Objects.equals(this.teamType, groupSyncableChannels.teamType) &&
        Objects.equals(this.groupId, groupSyncableChannels.groupId) &&
        Objects.equals(this.autoAdd, groupSyncableChannels.autoAdd) &&
        Objects.equals(this.createAt, groupSyncableChannels.createAt) &&
        Objects.equals(this.deleteAt, groupSyncableChannels.deleteAt) &&
        Objects.equals(this.updateAt, groupSyncableChannels.updateAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, channelDisplayName, channelType, teamId, teamDisplayName, teamType, groupId, autoAdd, createAt, deleteAt, updateAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupSyncableChannels {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    channelDisplayName: ").append(toIndentedString(channelDisplayName)).append("\n");
    sb.append("    channelType: ").append(toIndentedString(channelType)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    teamDisplayName: ").append(toIndentedString(teamDisplayName)).append("\n");
    sb.append("    teamType: ").append(toIndentedString(teamType)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    autoAdd: ").append(toIndentedString(autoAdd)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
