/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * IncomingHookIdBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class IncomingHookIdBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("icon_url")
  private String iconUrl = null;

  public IncomingHookIdBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Incoming webhook GUID
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IncomingHookIdBody channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The ID of a public channel or private group that receives the webhook payloads.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public IncomingHookIdBody displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name for this incoming webhook
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public IncomingHookIdBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description for this incoming webhook
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public IncomingHookIdBody username(String username) {
    this.username = username;
    return this;
  }

   /**
   * The username this incoming webhook will post as.
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public IncomingHookIdBody iconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
    return this;
  }

   /**
   * The profile picture this incoming webhook will use when posting.
   * @return iconUrl
  **/
  public String getIconUrl() {
    return iconUrl;
  }

  public void setIconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IncomingHookIdBody incomingHookIdBody = (IncomingHookIdBody) o;
    return Objects.equals(this.id, incomingHookIdBody.id) &&
        Objects.equals(this.channelId, incomingHookIdBody.channelId) &&
        Objects.equals(this.displayName, incomingHookIdBody.displayName) &&
        Objects.equals(this.description, incomingHookIdBody.description) &&
        Objects.equals(this.username, incomingHookIdBody.username) &&
        Objects.equals(this.iconUrl, incomingHookIdBody.iconUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, channelId, displayName, description, username, iconUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IncomingHookIdBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
