/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.User;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class InlineResponse200 {
  @JsonProperty("&lt;CHANNEL_ID&gt;")
  private List<User> CHANNEL_ID = null;

  public InlineResponse200 CHANNEL_ID(List<User> CHANNEL_ID) {
    this.CHANNEL_ID = CHANNEL_ID;
    return this;
  }

  public InlineResponse200 addCHANNELIDItem(User CHANNEL_IDItem) {
    if (this.CHANNEL_ID == null) {
      this.CHANNEL_ID = new ArrayList<>();
    }
    this.CHANNEL_ID.add(CHANNEL_IDItem);
    return this;
  }

   /**
   * Get CHANNEL_ID
   * @return CHANNEL_ID
  **/
  public List<User> getCHANNELID() {
    return CHANNEL_ID;
  }

  public void setCHANNELID(List<User> CHANNEL_ID) {
    this.CHANNEL_ID = CHANNEL_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.CHANNEL_ID, inlineResponse200.CHANNEL_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CHANNEL_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    CHANNEL_ID: ").append(toIndentedString(CHANNEL_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
