/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse20019
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class InlineResponse20019 {
  @JsonProperty("item")
  private String item = null;

  @JsonProperty("hint")
  private String hint = null;

  @JsonProperty("helptext")
  private String helptext = null;

  public InlineResponse20019 item(String item) {
    this.item = item;
    return this;
  }

   /**
   * A string containing a pair of integers separated by a space. The first integer is the index of the checklist; the second is the index of the item within the checklist.
   * @return item
  **/
  public String getItem() {
    return item;
  }

  public void setItem(String item) {
    this.item = item;
  }

  public InlineResponse20019 hint(String hint) {
    this.hint = hint;
    return this;
  }

   /**
   * The title of the corresponding item.
   * @return hint
  **/
  public String getHint() {
    return hint;
  }

  public void setHint(String hint) {
    this.hint = hint;
  }

  public InlineResponse20019 helptext(String helptext) {
    this.helptext = helptext;
    return this;
  }

   /**
   * Always the value \&quot;Check/uncheck this item\&quot;.
   * @return helptext
  **/
  public String getHelptext() {
    return helptext;
  }

  public void setHelptext(String helptext) {
    this.helptext = helptext;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20019 inlineResponse20019 = (InlineResponse20019) o;
    return Objects.equals(this.item, inlineResponse20019.item) &&
        Objects.equals(this.hint, inlineResponse20019.hint) &&
        Objects.equals(this.helptext, inlineResponse20019.helptext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(item, hint, helptext);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20019 {\n");
    
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    hint: ").append(toIndentedString(hint)).append("\n");
    sb.append("    helptext: ").append(toIndentedString(helptext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
