/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.PluginManifest;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20017
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class InlineResponse20017 {
  @JsonProperty("active")
  private List<PluginManifest> active = null;

  @JsonProperty("inactive")
  private List<PluginManifest> inactive = null;

  public InlineResponse20017 active(List<PluginManifest> active) {
    this.active = active;
    return this;
  }

  public InlineResponse20017 addActiveItem(PluginManifest activeItem) {
    if (this.active == null) {
      this.active = new ArrayList<>();
    }
    this.active.add(activeItem);
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  public List<PluginManifest> getActive() {
    return active;
  }

  public void setActive(List<PluginManifest> active) {
    this.active = active;
  }

  public InlineResponse20017 inactive(List<PluginManifest> inactive) {
    this.inactive = inactive;
    return this;
  }

  public InlineResponse20017 addInactiveItem(PluginManifest inactiveItem) {
    if (this.inactive == null) {
      this.inactive = new ArrayList<>();
    }
    this.inactive.add(inactiveItem);
    return this;
  }

   /**
   * Get inactive
   * @return inactive
  **/
  public List<PluginManifest> getInactive() {
    return inactive;
  }

  public void setInactive(List<PluginManifest> inactive) {
    this.inactive = inactive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017 inlineResponse20017 = (InlineResponse20017) o;
    return Objects.equals(this.active, inlineResponse20017.active) &&
        Objects.equals(this.inactive, inlineResponse20017.inactive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, inactive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017 {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    inactive: ").append(toIndentedString(inactive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
