/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Job
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Job {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("start_at")
  private Long startAt = null;

  @JsonProperty("last_activity_at")
  private Long lastActivityAt = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("progress")
  private Integer progress = null;

  @JsonProperty("data")
  private Object data = null;

  public Job id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique id of the job
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Job type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of job
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Job createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time at which the job was created
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public Job startAt(Long startAt) {
    this.startAt = startAt;
    return this;
  }

   /**
   * The time at which the job was started
   * @return startAt
  **/
  public Long getStartAt() {
    return startAt;
  }

  public void setStartAt(Long startAt) {
    this.startAt = startAt;
  }

  public Job lastActivityAt(Long lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
    return this;
  }

   /**
   * The last time at which the job had activity
   * @return lastActivityAt
  **/
  public Long getLastActivityAt() {
    return lastActivityAt;
  }

  public void setLastActivityAt(Long lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
  }

  public Job status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the job
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Job progress(Integer progress) {
    this.progress = progress;
    return this;
  }

   /**
   * The progress (as a percentage) of the job
   * @return progress
  **/
  public Integer getProgress() {
    return progress;
  }

  public void setProgress(Integer progress) {
    this.progress = progress;
  }

  public Job data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * A freeform data field containing additional information about the job
   * @return data
  **/
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Job job = (Job) o;
    return Objects.equals(this.id, job.id) &&
        Objects.equals(this.type, job.type) &&
        Objects.equals(this.createAt, job.createAt) &&
        Objects.equals(this.startAt, job.startAt) &&
        Objects.equals(this.lastActivityAt, job.lastActivityAt) &&
        Objects.equals(this.status, job.status) &&
        Objects.equals(this.progress, job.progress) &&
        Objects.equals(this.data, job.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, createAt, startAt, lastActivityAt, status, progress, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Job {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    lastActivityAt: ").append(toIndentedString(lastActivityAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
