/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A LDAP group
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class LDAPGroup {
  @JsonProperty("has_syncables")
  private Boolean hasSyncables = null;

  @JsonProperty("mattermost_group_id")
  private String mattermostGroupId = null;

  @JsonProperty("primary_key")
  private String primaryKey = null;

  @JsonProperty("name")
  private String name = null;

  public LDAPGroup hasSyncables(Boolean hasSyncables) {
    this.hasSyncables = hasSyncables;
    return this;
  }

   /**
   * Get hasSyncables
   * @return hasSyncables
  **/
  public Boolean isHasSyncables() {
    return hasSyncables;
  }

  public void setHasSyncables(Boolean hasSyncables) {
    this.hasSyncables = hasSyncables;
  }

  public LDAPGroup mattermostGroupId(String mattermostGroupId) {
    this.mattermostGroupId = mattermostGroupId;
    return this;
  }

   /**
   * Get mattermostGroupId
   * @return mattermostGroupId
  **/
  public String getMattermostGroupId() {
    return mattermostGroupId;
  }

  public void setMattermostGroupId(String mattermostGroupId) {
    this.mattermostGroupId = mattermostGroupId;
  }

  public LDAPGroup primaryKey(String primaryKey) {
    this.primaryKey = primaryKey;
    return this;
  }

   /**
   * Get primaryKey
   * @return primaryKey
  **/
  public String getPrimaryKey() {
    return primaryKey;
  }

  public void setPrimaryKey(String primaryKey) {
    this.primaryKey = primaryKey;
  }

  public LDAPGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LDAPGroup ldAPGroup = (LDAPGroup) o;
    return Objects.equals(this.hasSyncables, ldAPGroup.hasSyncables) &&
        Objects.equals(this.mattermostGroupId, ldAPGroup.mattermostGroupId) &&
        Objects.equals(this.primaryKey, ldAPGroup.primaryKey) &&
        Objects.equals(this.name, ldAPGroup.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasSyncables, mattermostGroupId, primaryKey, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LDAPGroup {\n");
    
    sb.append("    hasSyncables: ").append(toIndentedString(hasSyncables)).append("\n");
    sb.append("    mattermostGroupId: ").append(toIndentedString(mattermostGroupId)).append("\n");
    sb.append("    primaryKey: ").append(toIndentedString(primaryKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
