/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.LDAPGroup;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * A paged list of LDAP groups
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class LDAPGroupsPaged {
  @JsonProperty("count")
  private BigDecimal count = null;

  @JsonProperty("groups")
  private List<LDAPGroup> groups = null;

  public LDAPGroupsPaged count(BigDecimal count) {
    this.count = count;
    return this;
  }

   /**
   * Total number of groups
   * @return count
  **/
  public BigDecimal getCount() {
    return count;
  }

  public void setCount(BigDecimal count) {
    this.count = count;
  }

  public LDAPGroupsPaged groups(List<LDAPGroup> groups) {
    this.groups = groups;
    return this;
  }

  public LDAPGroupsPaged addGroupsItem(LDAPGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  public List<LDAPGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<LDAPGroup> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LDAPGroupsPaged ldAPGroupsPaged = (LDAPGroupsPaged) o;
    return Objects.equals(this.count, ldAPGroupsPaged.count) &&
        Objects.equals(this.groups, ldAPGroupsPaged.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, groups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LDAPGroupsPaged {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
