/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LoginSwitchBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class LoginSwitchBody {
  @JsonProperty("current_service")
  private String currentService = null;

  @JsonProperty("new_service")
  private String newService = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("mfa_code")
  private String mfaCode = null;

  @JsonProperty("ldap_id")
  private String ldapId = null;

  public LoginSwitchBody currentService(String currentService) {
    this.currentService = currentService;
    return this;
  }

   /**
   * The service the user currently uses to login
   * @return currentService
  **/
  public String getCurrentService() {
    return currentService;
  }

  public void setCurrentService(String currentService) {
    this.currentService = currentService;
  }

  public LoginSwitchBody newService(String newService) {
    this.newService = newService;
    return this;
  }

   /**
   * The service the user will use to login
   * @return newService
  **/
  public String getNewService() {
    return newService;
  }

  public void setNewService(String newService) {
    this.newService = newService;
  }

  public LoginSwitchBody email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email of the user
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public LoginSwitchBody password(String password) {
    this.password = password;
    return this;
  }

   /**
   * The password used with the current service
   * @return password
  **/
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public LoginSwitchBody mfaCode(String mfaCode) {
    this.mfaCode = mfaCode;
    return this;
  }

   /**
   * The MFA code of the current service
   * @return mfaCode
  **/
  public String getMfaCode() {
    return mfaCode;
  }

  public void setMfaCode(String mfaCode) {
    this.mfaCode = mfaCode;
  }

  public LoginSwitchBody ldapId(String ldapId) {
    this.ldapId = ldapId;
    return this;
  }

   /**
   * The LDAP/AD id of the user
   * @return ldapId
  **/
  public String getLdapId() {
    return ldapId;
  }

  public void setLdapId(String ldapId) {
    this.ldapId = ldapId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginSwitchBody loginSwitchBody = (LoginSwitchBody) o;
    return Objects.equals(this.currentService, loginSwitchBody.currentService) &&
        Objects.equals(this.newService, loginSwitchBody.newService) &&
        Objects.equals(this.email, loginSwitchBody.email) &&
        Objects.equals(this.password, loginSwitchBody.password) &&
        Objects.equals(this.mfaCode, loginSwitchBody.mfaCode) &&
        Objects.equals(this.ldapId, loginSwitchBody.ldapId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentService, newService, email, password, mfaCode, ldapId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginSwitchBody {\n");
    
    sb.append("    currentService: ").append(toIndentedString(currentService)).append("\n");
    sb.append("    newService: ").append(toIndentedString(newService)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    mfaCode: ").append(toIndentedString(mfaCode)).append("\n");
    sb.append("    ldapId: ").append(toIndentedString(ldapId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
