/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.PluginManifest;

import java.util.ArrayList;
import java.util.List;
/**
 * MarketplacePlugin
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class MarketplacePlugin {
  @JsonProperty("homepage_url")
  private String homepageUrl = null;

  @JsonProperty("icon_data")
  private String iconData = null;

  @JsonProperty("download_url")
  private String downloadUrl = null;

  @JsonProperty("release_notes_url")
  private String releaseNotesUrl = null;

  @JsonProperty("labels")
  private List<String> labels = null;

  @JsonProperty("signature")
  private String signature = null;

  @JsonProperty("manifest")
  private PluginManifest manifest = null;

  @JsonProperty("installed_version")
  private String installedVersion = null;

  public MarketplacePlugin homepageUrl(String homepageUrl) {
    this.homepageUrl = homepageUrl;
    return this;
  }

   /**
   * URL that leads to the homepage of the plugin.
   * @return homepageUrl
  **/
  public String getHomepageUrl() {
    return homepageUrl;
  }

  public void setHomepageUrl(String homepageUrl) {
    this.homepageUrl = homepageUrl;
  }

  public MarketplacePlugin iconData(String iconData) {
    this.iconData = iconData;
    return this;
  }

   /**
   * Base64 encoding of a plugin icon SVG.
   * @return iconData
  **/
  public String getIconData() {
    return iconData;
  }

  public void setIconData(String iconData) {
    this.iconData = iconData;
  }

  public MarketplacePlugin downloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

   /**
   * URL to download the plugin.
   * @return downloadUrl
  **/
  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  public MarketplacePlugin releaseNotesUrl(String releaseNotesUrl) {
    this.releaseNotesUrl = releaseNotesUrl;
    return this;
  }

   /**
   * URL that leads to the release notes of the plugin.
   * @return releaseNotesUrl
  **/
  public String getReleaseNotesUrl() {
    return releaseNotesUrl;
  }

  public void setReleaseNotesUrl(String releaseNotesUrl) {
    this.releaseNotesUrl = releaseNotesUrl;
  }

  public MarketplacePlugin labels(List<String> labels) {
    this.labels = labels;
    return this;
  }

  public MarketplacePlugin addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * A list of the plugin labels.
   * @return labels
  **/
  public List<String> getLabels() {
    return labels;
  }

  public void setLabels(List<String> labels) {
    this.labels = labels;
  }

  public MarketplacePlugin signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Base64 encoded signature of the plugin.
   * @return signature
  **/
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public MarketplacePlugin manifest(PluginManifest manifest) {
    this.manifest = manifest;
    return this;
  }

   /**
   * Get manifest
   * @return manifest
  **/
  public PluginManifest getManifest() {
    return manifest;
  }

  public void setManifest(PluginManifest manifest) {
    this.manifest = manifest;
  }

  public MarketplacePlugin installedVersion(String installedVersion) {
    this.installedVersion = installedVersion;
    return this;
  }

   /**
   * Version number of the already installed plugin, if any.
   * @return installedVersion
  **/
  public String getInstalledVersion() {
    return installedVersion;
  }

  public void setInstalledVersion(String installedVersion) {
    this.installedVersion = installedVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplacePlugin marketplacePlugin = (MarketplacePlugin) o;
    return Objects.equals(this.homepageUrl, marketplacePlugin.homepageUrl) &&
        Objects.equals(this.iconData, marketplacePlugin.iconData) &&
        Objects.equals(this.downloadUrl, marketplacePlugin.downloadUrl) &&
        Objects.equals(this.releaseNotesUrl, marketplacePlugin.releaseNotesUrl) &&
        Objects.equals(this.labels, marketplacePlugin.labels) &&
        Objects.equals(this.signature, marketplacePlugin.signature) &&
        Objects.equals(this.manifest, marketplacePlugin.manifest) &&
        Objects.equals(this.installedVersion, marketplacePlugin.installedVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(homepageUrl, iconData, downloadUrl, releaseNotesUrl, labels, signature, manifest, installedVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplacePlugin {\n");
    
    sb.append("    homepageUrl: ").append(toIndentedString(homepageUrl)).append("\n");
    sb.append("    iconData: ").append(toIndentedString(iconData)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    releaseNotesUrl: ").append(toIndentedString(releaseNotesUrl)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    manifest: ").append(toIndentedString(manifest)).append("\n");
    sb.append("    installedVersion: ").append(toIndentedString(installedVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
