/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Notice
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Notice {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("sysAdminOnly")
  private Boolean sysAdminOnly = null;

  @JsonProperty("teamAdminOnly")
  private Boolean teamAdminOnly = null;

  @JsonProperty("action")
  private String action = null;

  @JsonProperty("actionParam")
  private String actionParam = null;

  @JsonProperty("actionText")
  private String actionText = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("image")
  private String image = null;

  @JsonProperty("title")
  private String title = null;

  public Notice id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Notice ID
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Notice sysAdminOnly(Boolean sysAdminOnly) {
    this.sysAdminOnly = sysAdminOnly;
    return this;
  }

   /**
   * Does this notice apply only to sysadmins
   * @return sysAdminOnly
  **/
  public Boolean isSysAdminOnly() {
    return sysAdminOnly;
  }

  public void setSysAdminOnly(Boolean sysAdminOnly) {
    this.sysAdminOnly = sysAdminOnly;
  }

  public Notice teamAdminOnly(Boolean teamAdminOnly) {
    this.teamAdminOnly = teamAdminOnly;
    return this;
  }

   /**
   * Does this notice apply only to team admins
   * @return teamAdminOnly
  **/
  public Boolean isTeamAdminOnly() {
    return teamAdminOnly;
  }

  public void setTeamAdminOnly(Boolean teamAdminOnly) {
    this.teamAdminOnly = teamAdminOnly;
  }

  public Notice action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Optional action to perform on action button click. (defaults to closing the notice)
   * @return action
  **/
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public Notice actionParam(String actionParam) {
    this.actionParam = actionParam;
    return this;
  }

   /**
   * Optional action parameter.  Example: {\&quot;action\&quot;: \&quot;url\&quot;, actionParam: \&quot;/console/some-page\&quot;}
   * @return actionParam
  **/
  public String getActionParam() {
    return actionParam;
  }

  public void setActionParam(String actionParam) {
    this.actionParam = actionParam;
  }

  public Notice actionText(String actionText) {
    this.actionText = actionText;
    return this;
  }

   /**
   * Optional override for the action button text (defaults to OK)
   * @return actionText
  **/
  public String getActionText() {
    return actionText;
  }

  public void setActionText(String actionText) {
    this.actionText = actionText;
  }

  public Notice description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Notice content. Use {{Mattermost}} instead of plain text to support white-labeling. Text supports Markdown.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Notice image(String image) {
    this.image = image;
    return this;
  }

   /**
   * URL of image to display
   * @return image
  **/
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Notice title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Notice title. Use {{Mattermost}} instead of plain text to support white-labeling. Text supports Markdown.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notice notice = (Notice) o;
    return Objects.equals(this.id, notice.id) &&
        Objects.equals(this.sysAdminOnly, notice.sysAdminOnly) &&
        Objects.equals(this.teamAdminOnly, notice.teamAdminOnly) &&
        Objects.equals(this.action, notice.action) &&
        Objects.equals(this.actionParam, notice.actionParam) &&
        Objects.equals(this.actionText, notice.actionText) &&
        Objects.equals(this.description, notice.description) &&
        Objects.equals(this.image, notice.image) &&
        Objects.equals(this.title, notice.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sysAdminOnly, teamAdminOnly, action, actionParam, actionText, description, image, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notice {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sysAdminOnly: ").append(toIndentedString(sysAdminOnly)).append("\n");
    sb.append("    teamAdminOnly: ").append(toIndentedString(teamAdminOnly)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    actionParam: ").append(toIndentedString(actionParam)).append("\n");
    sb.append("    actionText: ").append(toIndentedString(actionText)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
