/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.OpenGraphArticleAuthors;

import java.util.ArrayList;
import java.util.List;
/**
 * Book object used in OpenGraph metadata of a webpage, if type is book
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class OpenGraphBook {
  @JsonProperty("isbn")
  private String isbn = null;

  @JsonProperty("release_date")
  private String releaseDate = null;

  @JsonProperty("tags")
  private List<String> tags = null;

  @JsonProperty("authors")
  private List<OpenGraphArticleAuthors> authors = null;

  public OpenGraphBook isbn(String isbn) {
    this.isbn = isbn;
    return this;
  }

   /**
   * Get isbn
   * @return isbn
  **/
  public String getIsbn() {
    return isbn;
  }

  public void setIsbn(String isbn) {
    this.isbn = isbn;
  }

  public OpenGraphBook releaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }

  public OpenGraphBook tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public OpenGraphBook addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public OpenGraphBook authors(List<OpenGraphArticleAuthors> authors) {
    this.authors = authors;
    return this;
  }

  public OpenGraphBook addAuthorsItem(OpenGraphArticleAuthors authorsItem) {
    if (this.authors == null) {
      this.authors = new ArrayList<>();
    }
    this.authors.add(authorsItem);
    return this;
  }

   /**
   * Get authors
   * @return authors
  **/
  public List<OpenGraphArticleAuthors> getAuthors() {
    return authors;
  }

  public void setAuthors(List<OpenGraphArticleAuthors> authors) {
    this.authors = authors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenGraphBook openGraphBook = (OpenGraphBook) o;
    return Objects.equals(this.isbn, openGraphBook.isbn) &&
        Objects.equals(this.releaseDate, openGraphBook.releaseDate) &&
        Objects.equals(this.tags, openGraphBook.tags) &&
        Objects.equals(this.authors, openGraphBook.authors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isbn, releaseDate, tags, authors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenGraphBook {\n");
    
    sb.append("    isbn: ").append(toIndentedString(isbn)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    authors: ").append(toIndentedString(authors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
