/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentConfirmBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class PaymentConfirmBody {
  @JsonProperty("stripe_setup_intent_id")
  private String stripeSetupIntentId = null;

  public PaymentConfirmBody stripeSetupIntentId(String stripeSetupIntentId) {
    this.stripeSetupIntentId = stripeSetupIntentId;
    return this;
  }

   /**
   * Get stripeSetupIntentId
   * @return stripeSetupIntentId
  **/
  public String getStripeSetupIntentId() {
    return stripeSetupIntentId;
  }

  public void setStripeSetupIntentId(String stripeSetupIntentId) {
    this.stripeSetupIntentId = stripeSetupIntentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentConfirmBody paymentConfirmBody = (PaymentConfirmBody) o;
    return Objects.equals(this.stripeSetupIntentId, paymentConfirmBody.stripeSetupIntentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stripeSetupIntentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentConfirmBody {\n");
    
    sb.append("    stripeSetupIntentId: ").append(toIndentedString(stripeSetupIntentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
