/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Paths to executable binaries, specifying multiple entry points for different platforms when bundled together in a single plugin.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class PluginManifestServerExecutables {
  @JsonProperty("linux-amd64")
  private String linuxAmd64 = null;

  @JsonProperty("darwin-amd64")
  private String darwinAmd64 = null;

  @JsonProperty("windows-amd64")
  private String windowsAmd64 = null;

  public PluginManifestServerExecutables linuxAmd64(String linuxAmd64) {
    this.linuxAmd64 = linuxAmd64;
    return this;
  }

   /**
   * Get linuxAmd64
   * @return linuxAmd64
  **/
  public String getLinuxAmd64() {
    return linuxAmd64;
  }

  public void setLinuxAmd64(String linuxAmd64) {
    this.linuxAmd64 = linuxAmd64;
  }

  public PluginManifestServerExecutables darwinAmd64(String darwinAmd64) {
    this.darwinAmd64 = darwinAmd64;
    return this;
  }

   /**
   * Get darwinAmd64
   * @return darwinAmd64
  **/
  public String getDarwinAmd64() {
    return darwinAmd64;
  }

  public void setDarwinAmd64(String darwinAmd64) {
    this.darwinAmd64 = darwinAmd64;
  }

  public PluginManifestServerExecutables windowsAmd64(String windowsAmd64) {
    this.windowsAmd64 = windowsAmd64;
    return this;
  }

   /**
   * Get windowsAmd64
   * @return windowsAmd64
  **/
  public String getWindowsAmd64() {
    return windowsAmd64;
  }

  public void setWindowsAmd64(String windowsAmd64) {
    this.windowsAmd64 = windowsAmd64;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PluginManifestServerExecutables pluginManifestServerExecutables = (PluginManifestServerExecutables) o;
    return Objects.equals(this.linuxAmd64, pluginManifestServerExecutables.linuxAmd64) &&
        Objects.equals(this.darwinAmd64, pluginManifestServerExecutables.darwinAmd64) &&
        Objects.equals(this.windowsAmd64, pluginManifestServerExecutables.windowsAmd64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linuxAmd64, darwinAmd64, windowsAmd64);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PluginManifestServerExecutables {\n");
    
    sb.append("    linuxAmd64: ").append(toIndentedString(linuxAmd64)).append("\n");
    sb.append("    darwinAmd64: ").append(toIndentedString(darwinAmd64)).append("\n");
    sb.append("    windowsAmd64: ").append(toIndentedString(windowsAmd64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
