/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Pluginsplaybooksapiv0playbooksItems
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Pluginsplaybooksapiv0playbooksItems {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("command")
  private String command = null;

  @JsonProperty("description")
  private String description = null;

  public Pluginsplaybooksapiv0playbooksItems title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the checklist item.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Pluginsplaybooksapiv0playbooksItems command(String command) {
    this.command = command;
    return this;
  }

   /**
   * The slash command associated with this item. If the item has no slash command associated, this is an empty string
   * @return command
  **/
  public String getCommand() {
    return command;
  }

  public void setCommand(String command) {
    this.command = command;
  }

  public Pluginsplaybooksapiv0playbooksItems description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A detailed description of the checklist item, formatted with Markdown.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pluginsplaybooksapiv0playbooksItems pluginsplaybooksapiv0playbooksItems = (Pluginsplaybooksapiv0playbooksItems) o;
    return Objects.equals(this.title, pluginsplaybooksapiv0playbooksItems.title) &&
        Objects.equals(this.command, pluginsplaybooksapiv0playbooksItems.command) &&
        Objects.equals(this.description, pluginsplaybooksapiv0playbooksItems.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, command, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pluginsplaybooksapiv0playbooksItems {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
