/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostsSearchBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class PostsSearchBody {
  @JsonProperty("terms")
  private String terms = null;

  @JsonProperty("is_or_search")
  private Boolean isOrSearch = null;

  @JsonProperty("time_zone_offset")
  private Integer timeZoneOffset = 0;

  @JsonProperty("include_deleted_channels")
  private Boolean includeDeletedChannels = null;

  @JsonProperty("page")
  private Integer page = 0;

  @JsonProperty("per_page")
  private Integer perPage = 60;

  public PostsSearchBody terms(String terms) {
    this.terms = terms;
    return this;
  }

   /**
   * The search terms as inputed by the user. To search for posts from a user include &#x60;from:someusername&#x60;, using a user&#x27;s username. To search in a specific channel include &#x60;in:somechannel&#x60;, using the channel name (not the display name).
   * @return terms
  **/
  public String getTerms() {
    return terms;
  }

  public void setTerms(String terms) {
    this.terms = terms;
  }

  public PostsSearchBody isOrSearch(Boolean isOrSearch) {
    this.isOrSearch = isOrSearch;
    return this;
  }

   /**
   * Set to true if an Or search should be performed vs an And search.
   * @return isOrSearch
  **/
  public Boolean isIsOrSearch() {
    return isOrSearch;
  }

  public void setIsOrSearch(Boolean isOrSearch) {
    this.isOrSearch = isOrSearch;
  }

  public PostsSearchBody timeZoneOffset(Integer timeZoneOffset) {
    this.timeZoneOffset = timeZoneOffset;
    return this;
  }

   /**
   * Offset from UTC of user timezone for date searches.
   * @return timeZoneOffset
  **/
  public Integer getTimeZoneOffset() {
    return timeZoneOffset;
  }

  public void setTimeZoneOffset(Integer timeZoneOffset) {
    this.timeZoneOffset = timeZoneOffset;
  }

  public PostsSearchBody includeDeletedChannels(Boolean includeDeletedChannels) {
    this.includeDeletedChannels = includeDeletedChannels;
    return this;
  }

   /**
   * Set to true if deleted channels should be included in the search. (archived channels)
   * @return includeDeletedChannels
  **/
  public Boolean isIncludeDeletedChannels() {
    return includeDeletedChannels;
  }

  public void setIncludeDeletedChannels(Boolean includeDeletedChannels) {
    this.includeDeletedChannels = includeDeletedChannels;
  }

  public PostsSearchBody page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * The page to select. (Only works with Elasticsearch)
   * @return page
  **/
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public PostsSearchBody perPage(Integer perPage) {
    this.perPage = perPage;
    return this;
  }

   /**
   * The number of posts per page. (Only works with Elasticsearch)
   * @return perPage
  **/
  public Integer getPerPage() {
    return perPage;
  }

  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostsSearchBody postsSearchBody = (PostsSearchBody) o;
    return Objects.equals(this.terms, postsSearchBody.terms) &&
        Objects.equals(this.isOrSearch, postsSearchBody.isOrSearch) &&
        Objects.equals(this.timeZoneOffset, postsSearchBody.timeZoneOffset) &&
        Objects.equals(this.includeDeletedChannels, postsSearchBody.includeDeletedChannels) &&
        Objects.equals(this.page, postsSearchBody.page) &&
        Objects.equals(this.perPage, postsSearchBody.perPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(terms, isOrSearch, timeZoneOffset, includeDeletedChannels, page, perPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostsSearchBody {\n");
    
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    isOrSearch: ").append(toIndentedString(isOrSearch)).append("\n");
    sb.append("    timeZoneOffset: ").append(toIndentedString(timeZoneOffset)).append("\n");
    sb.append("    includeDeletedChannels: ").append(toIndentedString(includeDeletedChannels)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
