/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostAcknowledgement
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class PostAcknowledgement {
  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("post_id")
  private String postId = null;

  @JsonProperty("acknowledged_at")
  private Long acknowledgedAt = null;

  public PostAcknowledgement userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the user that made this acknowledgement.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public PostAcknowledgement postId(String postId) {
    this.postId = postId;
    return this;
  }

   /**
   * The ID of the post to which this acknowledgement was made.
   * @return postId
  **/
  public String getPostId() {
    return postId;
  }

  public void setPostId(String postId) {
    this.postId = postId;
  }

  public PostAcknowledgement acknowledgedAt(Long acknowledgedAt) {
    this.acknowledgedAt = acknowledgedAt;
    return this;
  }

   /**
   * The time in milliseconds in which this acknowledgement was made.
   * @return acknowledgedAt
  **/
  public Long getAcknowledgedAt() {
    return acknowledgedAt;
  }

  public void setAcknowledgedAt(Long acknowledgedAt) {
    this.acknowledgedAt = acknowledgedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAcknowledgement postAcknowledgement = (PostAcknowledgement) o;
    return Objects.equals(this.userId, postAcknowledgement.userId) &&
        Objects.equals(this.postId, postAcknowledgement.postId) &&
        Objects.equals(this.acknowledgedAt, postAcknowledgement.acknowledgedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, postId, acknowledgedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAcknowledgement {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
    sb.append("    acknowledgedAt: ").append(toIndentedString(acknowledgedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
