/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PostIdPatchBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class PostIdPatchBody {
  @JsonProperty("is_pinned")
  private Boolean isPinned = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("file_ids")
  private List<String> fileIds = null;

  @JsonProperty("has_reactions")
  private Boolean hasReactions = null;

  @JsonProperty("props")
  private String props = null;

  public PostIdPatchBody isPinned(Boolean isPinned) {
    this.isPinned = isPinned;
    return this;
  }

   /**
   * Set to &#x60;true&#x60; to pin the post to the channel it is in
   * @return isPinned
  **/
  public Boolean isIsPinned() {
    return isPinned;
  }

  public void setIsPinned(Boolean isPinned) {
    this.isPinned = isPinned;
  }

  public PostIdPatchBody message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The message text of the post
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public PostIdPatchBody fileIds(List<String> fileIds) {
    this.fileIds = fileIds;
    return this;
  }

  public PostIdPatchBody addFileIdsItem(String fileIdsItem) {
    if (this.fileIds == null) {
      this.fileIds = new ArrayList<>();
    }
    this.fileIds.add(fileIdsItem);
    return this;
  }

   /**
   * The list of files attached to this post
   * @return fileIds
  **/
  public List<String> getFileIds() {
    return fileIds;
  }

  public void setFileIds(List<String> fileIds) {
    this.fileIds = fileIds;
  }

  public PostIdPatchBody hasReactions(Boolean hasReactions) {
    this.hasReactions = hasReactions;
    return this;
  }

   /**
   * Set to &#x60;true&#x60; if the post has reactions to it
   * @return hasReactions
  **/
  public Boolean isHasReactions() {
    return hasReactions;
  }

  public void setHasReactions(Boolean hasReactions) {
    this.hasReactions = hasReactions;
  }

  public PostIdPatchBody props(String props) {
    this.props = props;
    return this;
  }

   /**
   * A general JSON property bag to attach to the post
   * @return props
  **/
  public String getProps() {
    return props;
  }

  public void setProps(String props) {
    this.props = props;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostIdPatchBody postIdPatchBody = (PostIdPatchBody) o;
    return Objects.equals(this.isPinned, postIdPatchBody.isPinned) &&
        Objects.equals(this.message, postIdPatchBody.message) &&
        Objects.equals(this.fileIds, postIdPatchBody.fileIds) &&
        Objects.equals(this.hasReactions, postIdPatchBody.hasReactions) &&
        Objects.equals(this.props, postIdPatchBody.props);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isPinned, message, fileIds, hasReactions, props);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostIdPatchBody {\n");
    
    sb.append("    isPinned: ").append(toIndentedString(isPinned)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    fileIds: ").append(toIndentedString(fileIds)).append("\n");
    sb.append("    hasReactions: ").append(toIndentedString(hasReactions)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
