/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.Apiv4postsephemeralPost;

/**
 * PostsEphemeralBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class PostsEphemeralBody {
  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("post")
  private Apiv4postsephemeralPost post = null;

  public PostsEphemeralBody userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The target user id for the ephemeral post
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public PostsEphemeralBody post(Apiv4postsephemeralPost post) {
    this.post = post;
    return this;
  }

   /**
   * Get post
   * @return post
  **/
  public Apiv4postsephemeralPost getPost() {
    return post;
  }

  public void setPost(Apiv4postsephemeralPost post) {
    this.post = post;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostsEphemeralBody postsEphemeralBody = (PostsEphemeralBody) o;
    return Objects.equals(this.userId, postsEphemeralBody.userId) &&
        Objects.equals(this.post, postsEphemeralBody.post);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, post);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostsEphemeralBody {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    post: ").append(toIndentedString(post)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
