/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RemoteClusterInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class RemoteClusterInfo {
  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("last_ping_at")
  private Long lastPingAt = null;

  public RemoteClusterInfo displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name for the remote cluster
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public RemoteClusterInfo createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time in milliseconds a remote cluster was created
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public RemoteClusterInfo lastPingAt(Long lastPingAt) {
    this.lastPingAt = lastPingAt;
    return this;
  }

   /**
   * The time in milliseconds a remote cluster was last pinged successfully
   * @return lastPingAt
  **/
  public Long getLastPingAt() {
    return lastPingAt;
  }

  public void setLastPingAt(Long lastPingAt) {
    this.lastPingAt = lastPingAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteClusterInfo remoteClusterInfo = (RemoteClusterInfo) o;
    return Objects.equals(this.displayName, remoteClusterInfo.displayName) &&
        Objects.equals(this.createAt, remoteClusterInfo.createAt) &&
        Objects.equals(this.lastPingAt, remoteClusterInfo.lastPingAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, createAt, lastPingAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteClusterInfo {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    lastPingAt: ").append(toIndentedString(lastPingAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
