/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Scheme
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class Scheme {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("update_at")
  private Long updateAt = null;

  @JsonProperty("delete_at")
  private Long deleteAt = null;

  @JsonProperty("scope")
  private String scope = null;

  @JsonProperty("default_team_admin_role")
  private String defaultTeamAdminRole = null;

  @JsonProperty("default_team_user_role")
  private String defaultTeamUserRole = null;

  @JsonProperty("default_channel_admin_role")
  private String defaultChannelAdminRole = null;

  @JsonProperty("default_channel_user_role")
  private String defaultChannelUserRole = null;

  public Scheme id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the scheme.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Scheme name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The human readable name for the scheme.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Scheme description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A human readable description of the scheme.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Scheme createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time at which the scheme was created.
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public Scheme updateAt(Long updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * The time at which the scheme was last updated.
   * @return updateAt
  **/
  public Long getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Long updateAt) {
    this.updateAt = updateAt;
  }

  public Scheme deleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * The time at which the scheme was deleted.
   * @return deleteAt
  **/
  public Long getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(Long deleteAt) {
    this.deleteAt = deleteAt;
  }

  public Scheme scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * The scope to which this scheme can be applied, either \&quot;team\&quot; or \&quot;channel\&quot;.
   * @return scope
  **/
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public Scheme defaultTeamAdminRole(String defaultTeamAdminRole) {
    this.defaultTeamAdminRole = defaultTeamAdminRole;
    return this;
  }

   /**
   * The id of the default team admin role for this scheme.
   * @return defaultTeamAdminRole
  **/
  public String getDefaultTeamAdminRole() {
    return defaultTeamAdminRole;
  }

  public void setDefaultTeamAdminRole(String defaultTeamAdminRole) {
    this.defaultTeamAdminRole = defaultTeamAdminRole;
  }

  public Scheme defaultTeamUserRole(String defaultTeamUserRole) {
    this.defaultTeamUserRole = defaultTeamUserRole;
    return this;
  }

   /**
   * The id of the default team user role for this scheme.
   * @return defaultTeamUserRole
  **/
  public String getDefaultTeamUserRole() {
    return defaultTeamUserRole;
  }

  public void setDefaultTeamUserRole(String defaultTeamUserRole) {
    this.defaultTeamUserRole = defaultTeamUserRole;
  }

  public Scheme defaultChannelAdminRole(String defaultChannelAdminRole) {
    this.defaultChannelAdminRole = defaultChannelAdminRole;
    return this;
  }

   /**
   * The id of the default channel admin role for this scheme.
   * @return defaultChannelAdminRole
  **/
  public String getDefaultChannelAdminRole() {
    return defaultChannelAdminRole;
  }

  public void setDefaultChannelAdminRole(String defaultChannelAdminRole) {
    this.defaultChannelAdminRole = defaultChannelAdminRole;
  }

  public Scheme defaultChannelUserRole(String defaultChannelUserRole) {
    this.defaultChannelUserRole = defaultChannelUserRole;
    return this;
  }

   /**
   * The id of the default channel user role for this scheme.
   * @return defaultChannelUserRole
  **/
  public String getDefaultChannelUserRole() {
    return defaultChannelUserRole;
  }

  public void setDefaultChannelUserRole(String defaultChannelUserRole) {
    this.defaultChannelUserRole = defaultChannelUserRole;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scheme scheme = (Scheme) o;
    return Objects.equals(this.id, scheme.id) &&
        Objects.equals(this.name, scheme.name) &&
        Objects.equals(this.description, scheme.description) &&
        Objects.equals(this.createAt, scheme.createAt) &&
        Objects.equals(this.updateAt, scheme.updateAt) &&
        Objects.equals(this.deleteAt, scheme.deleteAt) &&
        Objects.equals(this.scope, scheme.scope) &&
        Objects.equals(this.defaultTeamAdminRole, scheme.defaultTeamAdminRole) &&
        Objects.equals(this.defaultTeamUserRole, scheme.defaultTeamUserRole) &&
        Objects.equals(this.defaultChannelAdminRole, scheme.defaultChannelAdminRole) &&
        Objects.equals(this.defaultChannelUserRole, scheme.defaultChannelUserRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, createAt, updateAt, deleteAt, scope, defaultTeamAdminRole, defaultTeamUserRole, defaultChannelAdminRole, defaultChannelUserRole);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scheme {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    defaultTeamAdminRole: ").append(toIndentedString(defaultTeamAdminRole)).append("\n");
    sb.append("    defaultTeamUserRole: ").append(toIndentedString(defaultTeamUserRole)).append("\n");
    sb.append("    defaultChannelAdminRole: ").append(toIndentedString(defaultChannelAdminRole)).append("\n");
    sb.append("    defaultChannelUserRole: ").append(toIndentedString(defaultChannelUserRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
