/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ServerLimits
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class ServerLimits {
  @JsonProperty("maxUsersLimit")
  private Long maxUsersLimit = null;

  @JsonProperty("activeUserCount")
  private Long activeUserCount = null;

  public ServerLimits maxUsersLimit(Long maxUsersLimit) {
    this.maxUsersLimit = maxUsersLimit;
    return this;
  }

   /**
   * The maximum number of users allowed on server
   * @return maxUsersLimit
  **/
  public Long getMaxUsersLimit() {
    return maxUsersLimit;
  }

  public void setMaxUsersLimit(Long maxUsersLimit) {
    this.maxUsersLimit = maxUsersLimit;
  }

  public ServerLimits activeUserCount(Long activeUserCount) {
    this.activeUserCount = activeUserCount;
    return this;
  }

   /**
   * The number of active users in the server
   * @return activeUserCount
  **/
  public Long getActiveUserCount() {
    return activeUserCount;
  }

  public void setActiveUserCount(Long activeUserCount) {
    this.activeUserCount = activeUserCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerLimits serverLimits = (ServerLimits) o;
    return Objects.equals(this.maxUsersLimit, serverLimits.maxUsersLimit) &&
        Objects.equals(this.activeUserCount, serverLimits.activeUserCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxUsersLimit, activeUserCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerLimits {\n");
    
    sb.append("    maxUsersLimit: ").append(toIndentedString(maxUsersLimit)).append("\n");
    sb.append("    activeUserCount: ").append(toIndentedString(activeUserCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
