/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubscriptionStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class SubscriptionStats {
  @JsonProperty("remaining_seats")
  private Integer remainingSeats = null;

  @JsonProperty("is_paid_tier")
  private String isPaidTier = null;

  public SubscriptionStats remainingSeats(Integer remainingSeats) {
    this.remainingSeats = remainingSeats;
    return this;
  }

   /**
   * Get remainingSeats
   * @return remainingSeats
  **/
  public Integer getRemainingSeats() {
    return remainingSeats;
  }

  public void setRemainingSeats(Integer remainingSeats) {
    this.remainingSeats = remainingSeats;
  }

  public SubscriptionStats isPaidTier(String isPaidTier) {
    this.isPaidTier = isPaidTier;
    return this;
  }

   /**
   * Get isPaidTier
   * @return isPaidTier
  **/
  public String getIsPaidTier() {
    return isPaidTier;
  }

  public void setIsPaidTier(String isPaidTier) {
    this.isPaidTier = isPaidTier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionStats subscriptionStats = (SubscriptionStats) o;
    return Objects.equals(this.remainingSeats, subscriptionStats.remainingSeats) &&
        Objects.equals(this.isPaidTier, subscriptionStats.isPaidTier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remainingSeats, isPaidTier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionStats {\n");
    
    sb.append("    remainingSeats: ").append(toIndentedString(remainingSeats)).append("\n");
    sb.append("    isPaidTier: ").append(toIndentedString(isPaidTier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
