/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SystemStatusResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class SystemStatusResponse {
  @JsonProperty("AndroidLatestVersion")
  private String androidLatestVersion = null;

  @JsonProperty("AndroidMinVersion")
  private String androidMinVersion = null;

  @JsonProperty("DesktopLatestVersion")
  private String desktopLatestVersion = null;

  @JsonProperty("DesktopMinVersion")
  private String desktopMinVersion = null;

  @JsonProperty("IosLatestVersion")
  private String iosLatestVersion = null;

  @JsonProperty("IosMinVersion")
  private String iosMinVersion = null;

  @JsonProperty("database_status")
  private String databaseStatus = null;

  @JsonProperty("filestore_status")
  private String filestoreStatus = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("CanReceiveNotifications")
  private String canReceiveNotifications = null;

  public SystemStatusResponse androidLatestVersion(String androidLatestVersion) {
    this.androidLatestVersion = androidLatestVersion;
    return this;
  }

   /**
   * Latest Android version supported
   * @return androidLatestVersion
  **/
  public String getAndroidLatestVersion() {
    return androidLatestVersion;
  }

  public void setAndroidLatestVersion(String androidLatestVersion) {
    this.androidLatestVersion = androidLatestVersion;
  }

  public SystemStatusResponse androidMinVersion(String androidMinVersion) {
    this.androidMinVersion = androidMinVersion;
    return this;
  }

   /**
   * Minimum Android version supported
   * @return androidMinVersion
  **/
  public String getAndroidMinVersion() {
    return androidMinVersion;
  }

  public void setAndroidMinVersion(String androidMinVersion) {
    this.androidMinVersion = androidMinVersion;
  }

  public SystemStatusResponse desktopLatestVersion(String desktopLatestVersion) {
    this.desktopLatestVersion = desktopLatestVersion;
    return this;
  }

   /**
   * Latest desktop version supported
   * @return desktopLatestVersion
  **/
  public String getDesktopLatestVersion() {
    return desktopLatestVersion;
  }

  public void setDesktopLatestVersion(String desktopLatestVersion) {
    this.desktopLatestVersion = desktopLatestVersion;
  }

  public SystemStatusResponse desktopMinVersion(String desktopMinVersion) {
    this.desktopMinVersion = desktopMinVersion;
    return this;
  }

   /**
   * Minimum desktop version supported
   * @return desktopMinVersion
  **/
  public String getDesktopMinVersion() {
    return desktopMinVersion;
  }

  public void setDesktopMinVersion(String desktopMinVersion) {
    this.desktopMinVersion = desktopMinVersion;
  }

  public SystemStatusResponse iosLatestVersion(String iosLatestVersion) {
    this.iosLatestVersion = iosLatestVersion;
    return this;
  }

   /**
   * Latest iOS version supported
   * @return iosLatestVersion
  **/
  public String getIosLatestVersion() {
    return iosLatestVersion;
  }

  public void setIosLatestVersion(String iosLatestVersion) {
    this.iosLatestVersion = iosLatestVersion;
  }

  public SystemStatusResponse iosMinVersion(String iosMinVersion) {
    this.iosMinVersion = iosMinVersion;
    return this;
  }

   /**
   * Minimum iOS version supported
   * @return iosMinVersion
  **/
  public String getIosMinVersion() {
    return iosMinVersion;
  }

  public void setIosMinVersion(String iosMinVersion) {
    this.iosMinVersion = iosMinVersion;
  }

  public SystemStatusResponse databaseStatus(String databaseStatus) {
    this.databaseStatus = databaseStatus;
    return this;
  }

   /**
   * Status of database (\&quot;OK\&quot; or \&quot;UNHEALTHY\&quot;). Included when get_server_status parameter set.
   * @return databaseStatus
  **/
  public String getDatabaseStatus() {
    return databaseStatus;
  }

  public void setDatabaseStatus(String databaseStatus) {
    this.databaseStatus = databaseStatus;
  }

  public SystemStatusResponse filestoreStatus(String filestoreStatus) {
    this.filestoreStatus = filestoreStatus;
    return this;
  }

   /**
   * Status of filestore (\&quot;OK\&quot; or \&quot;UNHEALTHY\&quot;). Included when get_server_status parameter set.
   * @return filestoreStatus
  **/
  public String getFilestoreStatus() {
    return filestoreStatus;
  }

  public void setFilestoreStatus(String filestoreStatus) {
    this.filestoreStatus = filestoreStatus;
  }

  public SystemStatusResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of server (\&quot;OK\&quot; or \&quot;UNHEALTHY\&quot;). Included when get_server_status parameter set.
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SystemStatusResponse canReceiveNotifications(String canReceiveNotifications) {
    this.canReceiveNotifications = canReceiveNotifications;
    return this;
  }

   /**
   * Whether the device id provided can receive notifications (\&quot;true\&quot;, \&quot;false\&quot; or \&quot;unknown\&quot;). Included when device_id parameter set.
   * @return canReceiveNotifications
  **/
  public String getCanReceiveNotifications() {
    return canReceiveNotifications;
  }

  public void setCanReceiveNotifications(String canReceiveNotifications) {
    this.canReceiveNotifications = canReceiveNotifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemStatusResponse systemStatusResponse = (SystemStatusResponse) o;
    return Objects.equals(this.androidLatestVersion, systemStatusResponse.androidLatestVersion) &&
        Objects.equals(this.androidMinVersion, systemStatusResponse.androidMinVersion) &&
        Objects.equals(this.desktopLatestVersion, systemStatusResponse.desktopLatestVersion) &&
        Objects.equals(this.desktopMinVersion, systemStatusResponse.desktopMinVersion) &&
        Objects.equals(this.iosLatestVersion, systemStatusResponse.iosLatestVersion) &&
        Objects.equals(this.iosMinVersion, systemStatusResponse.iosMinVersion) &&
        Objects.equals(this.databaseStatus, systemStatusResponse.databaseStatus) &&
        Objects.equals(this.filestoreStatus, systemStatusResponse.filestoreStatus) &&
        Objects.equals(this.status, systemStatusResponse.status) &&
        Objects.equals(this.canReceiveNotifications, systemStatusResponse.canReceiveNotifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(androidLatestVersion, androidMinVersion, desktopLatestVersion, desktopMinVersion, iosLatestVersion, iosMinVersion, databaseStatus, filestoreStatus, status, canReceiveNotifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemStatusResponse {\n");
    
    sb.append("    androidLatestVersion: ").append(toIndentedString(androidLatestVersion)).append("\n");
    sb.append("    androidMinVersion: ").append(toIndentedString(androidMinVersion)).append("\n");
    sb.append("    desktopLatestVersion: ").append(toIndentedString(desktopLatestVersion)).append("\n");
    sb.append("    desktopMinVersion: ").append(toIndentedString(desktopMinVersion)).append("\n");
    sb.append("    iosLatestVersion: ").append(toIndentedString(iosLatestVersion)).append("\n");
    sb.append("    iosMinVersion: ").append(toIndentedString(iosMinVersion)).append("\n");
    sb.append("    databaseStatus: ").append(toIndentedString(databaseStatus)).append("\n");
    sb.append("    filestoreStatus: ").append(toIndentedString(filestoreStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    canReceiveNotifications: ").append(toIndentedString(canReceiveNotifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
