/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TeamIdPatchBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class TeamIdPatchBody {
  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("company_name")
  private String companyName = null;

  @JsonProperty("invite_id")
  private String inviteId = null;

  @JsonProperty("allow_open_invite")
  private Boolean allowOpenInvite = null;

  public TeamIdPatchBody displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public TeamIdPatchBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TeamIdPatchBody companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public TeamIdPatchBody inviteId(String inviteId) {
    this.inviteId = inviteId;
    return this;
  }

   /**
   * Get inviteId
   * @return inviteId
  **/
  public String getInviteId() {
    return inviteId;
  }

  public void setInviteId(String inviteId) {
    this.inviteId = inviteId;
  }

  public TeamIdPatchBody allowOpenInvite(Boolean allowOpenInvite) {
    this.allowOpenInvite = allowOpenInvite;
    return this;
  }

   /**
   * Get allowOpenInvite
   * @return allowOpenInvite
  **/
  public Boolean isAllowOpenInvite() {
    return allowOpenInvite;
  }

  public void setAllowOpenInvite(Boolean allowOpenInvite) {
    this.allowOpenInvite = allowOpenInvite;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamIdPatchBody teamIdPatchBody = (TeamIdPatchBody) o;
    return Objects.equals(this.displayName, teamIdPatchBody.displayName) &&
        Objects.equals(this.description, teamIdPatchBody.description) &&
        Objects.equals(this.companyName, teamIdPatchBody.companyName) &&
        Objects.equals(this.inviteId, teamIdPatchBody.inviteId) &&
        Objects.equals(this.allowOpenInvite, teamIdPatchBody.allowOpenInvite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, description, companyName, inviteId, allowOpenInvite);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamIdPatchBody {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    inviteId: ").append(toIndentedString(inviteId)).append("\n");
    sb.append("    allowOpenInvite: ").append(toIndentedString(allowOpenInvite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
