/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * an object containing information used to keep track of a file upload.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class UploadSession {
  @JsonProperty("id")
  private String id = null;

  /**
   * The type of the upload.
   */
  public enum TypeEnum {
    ATTACHMENT("attachment"),
    IMPORT("import");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("filename")
  private String filename = null;

  @JsonProperty("file_size")
  private Long fileSize = null;

  @JsonProperty("file_offset")
  private Long fileOffset = null;

  public UploadSession id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for the upload.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UploadSession type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the upload.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public UploadSession createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time the upload was created in milliseconds.
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public UploadSession userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the user performing the upload.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public UploadSession channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The ID of the channel to upload to.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public UploadSession filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * The name of the file to upload.
   * @return filename
  **/
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public UploadSession fileSize(Long fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * The size of the file to upload in bytes.
   * @return fileSize
  **/
  public Long getFileSize() {
    return fileSize;
  }

  public void setFileSize(Long fileSize) {
    this.fileSize = fileSize;
  }

  public UploadSession fileOffset(Long fileOffset) {
    this.fileOffset = fileOffset;
    return this;
  }

   /**
   * The amount of data uploaded in bytes.
   * @return fileOffset
  **/
  public Long getFileOffset() {
    return fileOffset;
  }

  public void setFileOffset(Long fileOffset) {
    this.fileOffset = fileOffset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadSession uploadSession = (UploadSession) o;
    return Objects.equals(this.id, uploadSession.id) &&
        Objects.equals(this.type, uploadSession.type) &&
        Objects.equals(this.createAt, uploadSession.createAt) &&
        Objects.equals(this.userId, uploadSession.userId) &&
        Objects.equals(this.channelId, uploadSession.channelId) &&
        Objects.equals(this.filename, uploadSession.filename) &&
        Objects.equals(this.fileSize, uploadSession.fileSize) &&
        Objects.equals(this.fileOffset, uploadSession.fileOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, createAt, userId, channelId, filename, fileSize, fileOffset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadSession {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    fileOffset: ").append(toIndentedString(fileOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
