/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserAccessToken
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class UserAccessToken {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("token")
  private String token = null;

  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("description")
  private String description = null;

  public UserAccessToken id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the token
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UserAccessToken token(String token) {
    this.token = token;
    return this;
  }

   /**
   * The token used for authentication
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public UserAccessToken userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The user the token authenticates for
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public UserAccessToken description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the token usage
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAccessToken userAccessToken = (UserAccessToken) o;
    return Objects.equals(this.id, userAccessToken.id) &&
        Objects.equals(this.token, userAccessToken.token) &&
        Objects.equals(this.userId, userAccessToken.userId) &&
        Objects.equals(this.description, userAccessToken.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, token, userId, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAccessToken {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
