/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersLoginBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class UsersLoginBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("login_id")
  private String loginId = null;

  @JsonProperty("token")
  private String token = null;

  @JsonProperty("device_id")
  private String deviceId = null;

  @JsonProperty("ldap_only")
  private Boolean ldapOnly = null;

  @JsonProperty("password")
  private String password = null;

  public UsersLoginBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UsersLoginBody loginId(String loginId) {
    this.loginId = loginId;
    return this;
  }

   /**
   * Get loginId
   * @return loginId
  **/
  public String getLoginId() {
    return loginId;
  }

  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }

  public UsersLoginBody token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public UsersLoginBody deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public UsersLoginBody ldapOnly(Boolean ldapOnly) {
    this.ldapOnly = ldapOnly;
    return this;
  }

   /**
   * Get ldapOnly
   * @return ldapOnly
  **/
  public Boolean isLdapOnly() {
    return ldapOnly;
  }

  public void setLdapOnly(Boolean ldapOnly) {
    this.ldapOnly = ldapOnly;
  }

  public UsersLoginBody password(String password) {
    this.password = password;
    return this;
  }

   /**
   * The password used for email authentication.
   * @return password
  **/
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersLoginBody usersLoginBody = (UsersLoginBody) o;
    return Objects.equals(this.id, usersLoginBody.id) &&
        Objects.equals(this.loginId, usersLoginBody.loginId) &&
        Objects.equals(this.token, usersLoginBody.token) &&
        Objects.equals(this.deviceId, usersLoginBody.deviceId) &&
        Objects.equals(this.ldapOnly, usersLoginBody.ldapOnly) &&
        Objects.equals(this.password, usersLoginBody.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, loginId, token, deviceId, ldapOnly, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersLoginBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    ldapOnly: ").append(toIndentedString(ldapOnly)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
