/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserReport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class UserReport {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("create_at")
  private Long createAt = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("last_login_at")
  private Long lastLoginAt = null;

  @JsonProperty("last_status_at")
  private Long lastStatusAt = null;

  @JsonProperty("last_post_date")
  private Long lastPostDate = null;

  @JsonProperty("days_active")
  private Integer daysActive = null;

  @JsonProperty("total_posts")
  private Integer totalPosts = null;

  public UserReport id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UserReport createAt(Long createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time in milliseconds a user was created
   * @return createAt
  **/
  public Long getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Long createAt) {
    this.createAt = createAt;
  }

  public UserReport username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public UserReport email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserReport displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Calculated display name based on user
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public UserReport lastLoginAt(Long lastLoginAt) {
    this.lastLoginAt = lastLoginAt;
    return this;
  }

   /**
   * Last time the user was logged in
   * @return lastLoginAt
  **/
  public Long getLastLoginAt() {
    return lastLoginAt;
  }

  public void setLastLoginAt(Long lastLoginAt) {
    this.lastLoginAt = lastLoginAt;
  }

  public UserReport lastStatusAt(Long lastStatusAt) {
    this.lastStatusAt = lastStatusAt;
    return this;
  }

   /**
   * Last time the user&#x27;s status was updated
   * @return lastStatusAt
  **/
  public Long getLastStatusAt() {
    return lastStatusAt;
  }

  public void setLastStatusAt(Long lastStatusAt) {
    this.lastStatusAt = lastStatusAt;
  }

  public UserReport lastPostDate(Long lastPostDate) {
    this.lastPostDate = lastPostDate;
    return this;
  }

   /**
   * Last time the user made a post within the given date range
   * @return lastPostDate
  **/
  public Long getLastPostDate() {
    return lastPostDate;
  }

  public void setLastPostDate(Long lastPostDate) {
    this.lastPostDate = lastPostDate;
  }

  public UserReport daysActive(Integer daysActive) {
    this.daysActive = daysActive;
    return this;
  }

   /**
   * Total number of days a user posted within the given date range
   * @return daysActive
  **/
  public Integer getDaysActive() {
    return daysActive;
  }

  public void setDaysActive(Integer daysActive) {
    this.daysActive = daysActive;
  }

  public UserReport totalPosts(Integer totalPosts) {
    this.totalPosts = totalPosts;
    return this;
  }

   /**
   * Total number of posts made by a user within the given date range
   * @return totalPosts
  **/
  public Integer getTotalPosts() {
    return totalPosts;
  }

  public void setTotalPosts(Integer totalPosts) {
    this.totalPosts = totalPosts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserReport userReport = (UserReport) o;
    return Objects.equals(this.id, userReport.id) &&
        Objects.equals(this.createAt, userReport.createAt) &&
        Objects.equals(this.username, userReport.username) &&
        Objects.equals(this.email, userReport.email) &&
        Objects.equals(this.displayName, userReport.displayName) &&
        Objects.equals(this.lastLoginAt, userReport.lastLoginAt) &&
        Objects.equals(this.lastStatusAt, userReport.lastStatusAt) &&
        Objects.equals(this.lastPostDate, userReport.lastPostDate) &&
        Objects.equals(this.daysActive, userReport.daysActive) &&
        Objects.equals(this.totalPosts, userReport.totalPosts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createAt, username, email, displayName, lastLoginAt, lastStatusAt, lastPostDate, daysActive, totalPosts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserReport {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    lastLoginAt: ").append(toIndentedString(lastLoginAt)).append("\n");
    sb.append("    lastStatusAt: ").append(toIndentedString(lastStatusAt)).append("\n");
    sb.append("    lastPostDate: ").append(toIndentedString(lastPostDate)).append("\n");
    sb.append("    daysActive: ").append(toIndentedString(daysActive)).append("\n");
    sb.append("    totalPosts: ").append(toIndentedString(totalPosts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
