/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserNotifyProps
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class UserNotifyProps {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("push")
  private String push = null;

  @JsonProperty("desktop")
  private String desktop = null;

  @JsonProperty("desktop_sound")
  private String desktopSound = null;

  @JsonProperty("mention_keys")
  private String mentionKeys = null;

  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("first_name")
  private String firstName = null;

  public UserNotifyProps email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Set to \&quot;true\&quot; to enable email notifications, \&quot;false\&quot; to disable. Defaults to \&quot;true\&quot;.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserNotifyProps push(String push) {
    this.push = push;
    return this;
  }

   /**
   * Set to \&quot;all\&quot; to receive push notifications for all activity, \&quot;mention\&quot; for mentions and direct messages only, and \&quot;none\&quot; to disable. Defaults to \&quot;mention\&quot;.
   * @return push
  **/
  public String getPush() {
    return push;
  }

  public void setPush(String push) {
    this.push = push;
  }

  public UserNotifyProps desktop(String desktop) {
    this.desktop = desktop;
    return this;
  }

   /**
   * Set to \&quot;all\&quot; to receive desktop notifications for all activity, \&quot;mention\&quot; for mentions and direct messages only, and \&quot;none\&quot; to disable. Defaults to \&quot;all\&quot;.
   * @return desktop
  **/
  public String getDesktop() {
    return desktop;
  }

  public void setDesktop(String desktop) {
    this.desktop = desktop;
  }

  public UserNotifyProps desktopSound(String desktopSound) {
    this.desktopSound = desktopSound;
    return this;
  }

   /**
   * Set to \&quot;true\&quot; to enable sound on desktop notifications, \&quot;false\&quot; to disable. Defaults to \&quot;true\&quot;.
   * @return desktopSound
  **/
  public String getDesktopSound() {
    return desktopSound;
  }

  public void setDesktopSound(String desktopSound) {
    this.desktopSound = desktopSound;
  }

  public UserNotifyProps mentionKeys(String mentionKeys) {
    this.mentionKeys = mentionKeys;
    return this;
  }

   /**
   * A comma-separated list of words to count as mentions. Defaults to username and @username.
   * @return mentionKeys
  **/
  public String getMentionKeys() {
    return mentionKeys;
  }

  public void setMentionKeys(String mentionKeys) {
    this.mentionKeys = mentionKeys;
  }

  public UserNotifyProps channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Set to \&quot;true\&quot; to enable channel-wide notifications (@channel, @all, etc.), \&quot;false\&quot; to disable. Defaults to \&quot;true\&quot;.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public UserNotifyProps firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Set to \&quot;true\&quot; to enable mentions for first name. Defaults to \&quot;true\&quot; if a first name is set, \&quot;false\&quot; otherwise.
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserNotifyProps userNotifyProps = (UserNotifyProps) o;
    return Objects.equals(this.email, userNotifyProps.email) &&
        Objects.equals(this.push, userNotifyProps.push) &&
        Objects.equals(this.desktop, userNotifyProps.desktop) &&
        Objects.equals(this.desktopSound, userNotifyProps.desktopSound) &&
        Objects.equals(this.mentionKeys, userNotifyProps.mentionKeys) &&
        Objects.equals(this.channel, userNotifyProps.channel) &&
        Objects.equals(this.firstName, userNotifyProps.firstName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, push, desktop, desktopSound, mentionKeys, channel, firstName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserNotifyProps {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    push: ").append(toIndentedString(push)).append("\n");
    sb.append("    desktop: ").append(toIndentedString(desktop)).append("\n");
    sb.append("    desktopSound: ").append(toIndentedString(desktopSound)).append("\n");
    sb.append("    mentionKeys: ").append(toIndentedString(mentionKeys)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
