/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersSearchBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class UsersSearchBody {
  @JsonProperty("term")
  private String term = null;

  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("not_in_team_id")
  private String notInTeamId = null;

  @JsonProperty("in_channel_id")
  private String inChannelId = null;

  @JsonProperty("not_in_channel_id")
  private String notInChannelId = null;

  @JsonProperty("in_group_id")
  private String inGroupId = null;

  @JsonProperty("group_constrained")
  private Boolean groupConstrained = null;

  @JsonProperty("allow_inactive")
  private Boolean allowInactive = null;

  @JsonProperty("without_team")
  private Boolean withoutTeam = null;

  @JsonProperty("limit")
  private Integer limit = 100;

  public UsersSearchBody term(String term) {
    this.term = term;
    return this;
  }

   /**
   * The term to match against username, full name, nickname and email
   * @return term
  **/
  public String getTerm() {
    return term;
  }

  public void setTerm(String term) {
    this.term = term;
  }

  public UsersSearchBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * If provided, only search users on this team
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public UsersSearchBody notInTeamId(String notInTeamId) {
    this.notInTeamId = notInTeamId;
    return this;
  }

   /**
   * If provided, only search users not on this team
   * @return notInTeamId
  **/
  public String getNotInTeamId() {
    return notInTeamId;
  }

  public void setNotInTeamId(String notInTeamId) {
    this.notInTeamId = notInTeamId;
  }

  public UsersSearchBody inChannelId(String inChannelId) {
    this.inChannelId = inChannelId;
    return this;
  }

   /**
   * If provided, only search users in this channel
   * @return inChannelId
  **/
  public String getInChannelId() {
    return inChannelId;
  }

  public void setInChannelId(String inChannelId) {
    this.inChannelId = inChannelId;
  }

  public UsersSearchBody notInChannelId(String notInChannelId) {
    this.notInChannelId = notInChannelId;
    return this;
  }

   /**
   * If provided, only search users not in this channel. Must specifiy &#x60;team_id&#x60; when using this option
   * @return notInChannelId
  **/
  public String getNotInChannelId() {
    return notInChannelId;
  }

  public void setNotInChannelId(String notInChannelId) {
    this.notInChannelId = notInChannelId;
  }

  public UsersSearchBody inGroupId(String inGroupId) {
    this.inGroupId = inGroupId;
    return this;
  }

   /**
   * If provided, only search users in this group. Must have &#x60;manage_system&#x60; permission.
   * @return inGroupId
  **/
  public String getInGroupId() {
    return inGroupId;
  }

  public void setInGroupId(String inGroupId) {
    this.inGroupId = inGroupId;
  }

  public UsersSearchBody groupConstrained(Boolean groupConstrained) {
    this.groupConstrained = groupConstrained;
    return this;
  }

   /**
   * When used with &#x60;not_in_channel_id&#x60; or &#x60;not_in_team_id&#x60;, returns only the users that are allowed to join the channel or team based on its group constrains.
   * @return groupConstrained
  **/
  public Boolean isGroupConstrained() {
    return groupConstrained;
  }

  public void setGroupConstrained(Boolean groupConstrained) {
    this.groupConstrained = groupConstrained;
  }

  public UsersSearchBody allowInactive(Boolean allowInactive) {
    this.allowInactive = allowInactive;
    return this;
  }

   /**
   * When &#x60;true&#x60;, include deactivated users in the results
   * @return allowInactive
  **/
  public Boolean isAllowInactive() {
    return allowInactive;
  }

  public void setAllowInactive(Boolean allowInactive) {
    this.allowInactive = allowInactive;
  }

  public UsersSearchBody withoutTeam(Boolean withoutTeam) {
    this.withoutTeam = withoutTeam;
    return this;
  }

   /**
   * Set this to &#x60;true&#x60; if you would like to search for users that are not on a team. This option takes precendence over &#x60;team_id&#x60;, &#x60;in_channel_id&#x60;, and &#x60;not_in_channel_id&#x60;.
   * @return withoutTeam
  **/
  public Boolean isWithoutTeam() {
    return withoutTeam;
  }

  public void setWithoutTeam(Boolean withoutTeam) {
    this.withoutTeam = withoutTeam;
  }

  public UsersSearchBody limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * The maximum number of users to return in the results  __Available as of server version 5.6. Defaults to &#x60;100&#x60; if not provided or on an earlier server version.__ 
   * @return limit
  **/
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersSearchBody usersSearchBody = (UsersSearchBody) o;
    return Objects.equals(this.term, usersSearchBody.term) &&
        Objects.equals(this.teamId, usersSearchBody.teamId) &&
        Objects.equals(this.notInTeamId, usersSearchBody.notInTeamId) &&
        Objects.equals(this.inChannelId, usersSearchBody.inChannelId) &&
        Objects.equals(this.notInChannelId, usersSearchBody.notInChannelId) &&
        Objects.equals(this.inGroupId, usersSearchBody.inGroupId) &&
        Objects.equals(this.groupConstrained, usersSearchBody.groupConstrained) &&
        Objects.equals(this.allowInactive, usersSearchBody.allowInactive) &&
        Objects.equals(this.withoutTeam, usersSearchBody.withoutTeam) &&
        Objects.equals(this.limit, usersSearchBody.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(term, teamId, notInTeamId, inChannelId, notInChannelId, inGroupId, groupConstrained, allowInactive, withoutTeam, limit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersSearchBody {\n");
    
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    notInTeamId: ").append(toIndentedString(notInTeamId)).append("\n");
    sb.append("    inChannelId: ").append(toIndentedString(inChannelId)).append("\n");
    sb.append("    notInChannelId: ").append(toIndentedString(notInChannelId)).append("\n");
    sb.append("    inGroupId: ").append(toIndentedString(inGroupId)).append("\n");
    sb.append("    groupConstrained: ").append(toIndentedString(groupConstrained)).append("\n");
    sb.append("    allowInactive: ").append(toIndentedString(allowInactive)).append("\n");
    sb.append("    withoutTeam: ").append(toIndentedString(withoutTeam)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
