/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.Pluginsplaybooksapiv0playbooksChecklists;

import java.util.ArrayList;
import java.util.List;
/**
 * V0PlaybooksBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class V0PlaybooksBody {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("create_public_playbook_run")
  private Boolean createPublicPlaybookRun = null;

  @JsonProperty("public")
  private Boolean _public = null;

  @JsonProperty("checklists")
  private List<Pluginsplaybooksapiv0playbooksChecklists> checklists = new ArrayList<>();

  @JsonProperty("member_ids")
  private List<String> memberIds = new ArrayList<>();

  @JsonProperty("broadcast_channel_ids")
  private List<String> broadcastChannelIds = null;

  @JsonProperty("invited_user_ids")
  private List<String> invitedUserIds = null;

  @JsonProperty("invite_users_enabled")
  private Boolean inviteUsersEnabled = null;

  @JsonProperty("default_owner_id")
  private String defaultOwnerId = null;

  @JsonProperty("default_owner_enabled")
  private String defaultOwnerEnabled = null;

  @JsonProperty("announcement_channel_id")
  private String announcementChannelId = null;

  @JsonProperty("announcement_channel_enabled")
  private Boolean announcementChannelEnabled = null;

  @JsonProperty("webhook_on_creation_url")
  private String webhookOnCreationUrl = null;

  @JsonProperty("webhook_on_creation_enabled")
  private Boolean webhookOnCreationEnabled = null;

  @JsonProperty("webhook_on_status_update_url")
  private String webhookOnStatusUpdateUrl = null;

  @JsonProperty("webhook_on_status_update_enabled")
  private Boolean webhookOnStatusUpdateEnabled = null;

  public V0PlaybooksBody title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the playbook.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public V0PlaybooksBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the playbook.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public V0PlaybooksBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The identifier of the team where the playbook is in.
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public V0PlaybooksBody createPublicPlaybookRun(Boolean createPublicPlaybookRun) {
    this.createPublicPlaybookRun = createPublicPlaybookRun;
    return this;
  }

   /**
   * A boolean indicating whether the playbook runs created from this playbook should be public or private.
   * @return createPublicPlaybookRun
  **/
  public Boolean isCreatePublicPlaybookRun() {
    return createPublicPlaybookRun;
  }

  public void setCreatePublicPlaybookRun(Boolean createPublicPlaybookRun) {
    this.createPublicPlaybookRun = createPublicPlaybookRun;
  }

  public V0PlaybooksBody _public(Boolean _public) {
    this._public = _public;
    return this;
  }

   /**
   * A boolean indicating whether the playbook is licensed as public or private. Required &#x27;true&#x27; for free tier.
   * @return _public
  **/
  public Boolean isPublic() {
    return _public;
  }

  public void setPublic(Boolean _public) {
    this._public = _public;
  }

  public V0PlaybooksBody checklists(List<Pluginsplaybooksapiv0playbooksChecklists> checklists) {
    this.checklists = checklists;
    return this;
  }

  public V0PlaybooksBody addChecklistsItem(Pluginsplaybooksapiv0playbooksChecklists checklistsItem) {
    this.checklists.add(checklistsItem);
    return this;
  }

   /**
   * The stages defined by this playbook.
   * @return checklists
  **/
  public List<Pluginsplaybooksapiv0playbooksChecklists> getChecklists() {
    return checklists;
  }

  public void setChecklists(List<Pluginsplaybooksapiv0playbooksChecklists> checklists) {
    this.checklists = checklists;
  }

  public V0PlaybooksBody memberIds(List<String> memberIds) {
    this.memberIds = memberIds;
    return this;
  }

  public V0PlaybooksBody addMemberIdsItem(String memberIdsItem) {
    this.memberIds.add(memberIdsItem);
    return this;
  }

   /**
   * The identifiers of all the users that are members of this playbook.
   * @return memberIds
  **/
  public List<String> getMemberIds() {
    return memberIds;
  }

  public void setMemberIds(List<String> memberIds) {
    this.memberIds = memberIds;
  }

  public V0PlaybooksBody broadcastChannelIds(List<String> broadcastChannelIds) {
    this.broadcastChannelIds = broadcastChannelIds;
    return this;
  }

  public V0PlaybooksBody addBroadcastChannelIdsItem(String broadcastChannelIdsItem) {
    if (this.broadcastChannelIds == null) {
      this.broadcastChannelIds = new ArrayList<>();
    }
    this.broadcastChannelIds.add(broadcastChannelIdsItem);
    return this;
  }

   /**
   * The IDs of the channels where all the status updates will be broadcasted. The team of the broadcast channel must be the same as the playbook&#x27;s team.
   * @return broadcastChannelIds
  **/
  public List<String> getBroadcastChannelIds() {
    return broadcastChannelIds;
  }

  public void setBroadcastChannelIds(List<String> broadcastChannelIds) {
    this.broadcastChannelIds = broadcastChannelIds;
  }

  public V0PlaybooksBody invitedUserIds(List<String> invitedUserIds) {
    this.invitedUserIds = invitedUserIds;
    return this;
  }

  public V0PlaybooksBody addInvitedUserIdsItem(String invitedUserIdsItem) {
    if (this.invitedUserIds == null) {
      this.invitedUserIds = new ArrayList<>();
    }
    this.invitedUserIds.add(invitedUserIdsItem);
    return this;
  }

   /**
   * A list with the IDs of the members to be automatically invited to the playbook run&#x27;s channel as soon as the playbook run is created.
   * @return invitedUserIds
  **/
  public List<String> getInvitedUserIds() {
    return invitedUserIds;
  }

  public void setInvitedUserIds(List<String> invitedUserIds) {
    this.invitedUserIds = invitedUserIds;
  }

  public V0PlaybooksBody inviteUsersEnabled(Boolean inviteUsersEnabled) {
    this.inviteUsersEnabled = inviteUsersEnabled;
    return this;
  }

   /**
   * Boolean that indicates whether the members declared in invited_user_ids will be automatically invited.
   * @return inviteUsersEnabled
  **/
  public Boolean isInviteUsersEnabled() {
    return inviteUsersEnabled;
  }

  public void setInviteUsersEnabled(Boolean inviteUsersEnabled) {
    this.inviteUsersEnabled = inviteUsersEnabled;
  }

  public V0PlaybooksBody defaultOwnerId(String defaultOwnerId) {
    this.defaultOwnerId = defaultOwnerId;
    return this;
  }

   /**
   * User ID of the member that will be automatically assigned as owner as soon as the playbook run is created. If the member is not part of the playbook run&#x27;s channel or is not included in the invited_user_ids list, they will be automatically invited to the channel.
   * @return defaultOwnerId
  **/
  public String getDefaultOwnerId() {
    return defaultOwnerId;
  }

  public void setDefaultOwnerId(String defaultOwnerId) {
    this.defaultOwnerId = defaultOwnerId;
  }

  public V0PlaybooksBody defaultOwnerEnabled(String defaultOwnerEnabled) {
    this.defaultOwnerEnabled = defaultOwnerEnabled;
    return this;
  }

   /**
   * Boolean that indicates whether the member declared in default_owner_id will be automatically assigned as owner.
   * @return defaultOwnerEnabled
  **/
  public String getDefaultOwnerEnabled() {
    return defaultOwnerEnabled;
  }

  public void setDefaultOwnerEnabled(String defaultOwnerEnabled) {
    this.defaultOwnerEnabled = defaultOwnerEnabled;
  }

  public V0PlaybooksBody announcementChannelId(String announcementChannelId) {
    this.announcementChannelId = announcementChannelId;
    return this;
  }

   /**
   * ID of the channel where the playbook run will be automatically announced as soon as the playbook run is created.
   * @return announcementChannelId
  **/
  public String getAnnouncementChannelId() {
    return announcementChannelId;
  }

  public void setAnnouncementChannelId(String announcementChannelId) {
    this.announcementChannelId = announcementChannelId;
  }

  public V0PlaybooksBody announcementChannelEnabled(Boolean announcementChannelEnabled) {
    this.announcementChannelEnabled = announcementChannelEnabled;
    return this;
  }

   /**
   * Boolean that indicates whether the playbook run creation will be announced in the channel declared in announcement_channel_id.
   * @return announcementChannelEnabled
  **/
  public Boolean isAnnouncementChannelEnabled() {
    return announcementChannelEnabled;
  }

  public void setAnnouncementChannelEnabled(Boolean announcementChannelEnabled) {
    this.announcementChannelEnabled = announcementChannelEnabled;
  }

  public V0PlaybooksBody webhookOnCreationUrl(String webhookOnCreationUrl) {
    this.webhookOnCreationUrl = webhookOnCreationUrl;
    return this;
  }

   /**
   * An absolute URL where a POST request will be sent as soon as the playbook run is created. The allowed protocols are HTTP and HTTPS.
   * @return webhookOnCreationUrl
  **/
  public String getWebhookOnCreationUrl() {
    return webhookOnCreationUrl;
  }

  public void setWebhookOnCreationUrl(String webhookOnCreationUrl) {
    this.webhookOnCreationUrl = webhookOnCreationUrl;
  }

  public V0PlaybooksBody webhookOnCreationEnabled(Boolean webhookOnCreationEnabled) {
    this.webhookOnCreationEnabled = webhookOnCreationEnabled;
    return this;
  }

   /**
   * Boolean that indicates whether the webhook declared in webhook_on_creation_url will be automatically sent.
   * @return webhookOnCreationEnabled
  **/
  public Boolean isWebhookOnCreationEnabled() {
    return webhookOnCreationEnabled;
  }

  public void setWebhookOnCreationEnabled(Boolean webhookOnCreationEnabled) {
    this.webhookOnCreationEnabled = webhookOnCreationEnabled;
  }

  public V0PlaybooksBody webhookOnStatusUpdateUrl(String webhookOnStatusUpdateUrl) {
    this.webhookOnStatusUpdateUrl = webhookOnStatusUpdateUrl;
    return this;
  }

   /**
   * An absolute URL where a POST request will be sent as soon as the playbook run&#x27;s status is updated. The allowed protocols are HTTP and HTTPS.
   * @return webhookOnStatusUpdateUrl
  **/
  public String getWebhookOnStatusUpdateUrl() {
    return webhookOnStatusUpdateUrl;
  }

  public void setWebhookOnStatusUpdateUrl(String webhookOnStatusUpdateUrl) {
    this.webhookOnStatusUpdateUrl = webhookOnStatusUpdateUrl;
  }

  public V0PlaybooksBody webhookOnStatusUpdateEnabled(Boolean webhookOnStatusUpdateEnabled) {
    this.webhookOnStatusUpdateEnabled = webhookOnStatusUpdateEnabled;
    return this;
  }

   /**
   * Boolean that indicates whether the webhook declared in webhook_on_status_update_url will be automatically sent.
   * @return webhookOnStatusUpdateEnabled
  **/
  public Boolean isWebhookOnStatusUpdateEnabled() {
    return webhookOnStatusUpdateEnabled;
  }

  public void setWebhookOnStatusUpdateEnabled(Boolean webhookOnStatusUpdateEnabled) {
    this.webhookOnStatusUpdateEnabled = webhookOnStatusUpdateEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V0PlaybooksBody v0PlaybooksBody = (V0PlaybooksBody) o;
    return Objects.equals(this.title, v0PlaybooksBody.title) &&
        Objects.equals(this.description, v0PlaybooksBody.description) &&
        Objects.equals(this.teamId, v0PlaybooksBody.teamId) &&
        Objects.equals(this.createPublicPlaybookRun, v0PlaybooksBody.createPublicPlaybookRun) &&
        Objects.equals(this._public, v0PlaybooksBody._public) &&
        Objects.equals(this.checklists, v0PlaybooksBody.checklists) &&
        Objects.equals(this.memberIds, v0PlaybooksBody.memberIds) &&
        Objects.equals(this.broadcastChannelIds, v0PlaybooksBody.broadcastChannelIds) &&
        Objects.equals(this.invitedUserIds, v0PlaybooksBody.invitedUserIds) &&
        Objects.equals(this.inviteUsersEnabled, v0PlaybooksBody.inviteUsersEnabled) &&
        Objects.equals(this.defaultOwnerId, v0PlaybooksBody.defaultOwnerId) &&
        Objects.equals(this.defaultOwnerEnabled, v0PlaybooksBody.defaultOwnerEnabled) &&
        Objects.equals(this.announcementChannelId, v0PlaybooksBody.announcementChannelId) &&
        Objects.equals(this.announcementChannelEnabled, v0PlaybooksBody.announcementChannelEnabled) &&
        Objects.equals(this.webhookOnCreationUrl, v0PlaybooksBody.webhookOnCreationUrl) &&
        Objects.equals(this.webhookOnCreationEnabled, v0PlaybooksBody.webhookOnCreationEnabled) &&
        Objects.equals(this.webhookOnStatusUpdateUrl, v0PlaybooksBody.webhookOnStatusUpdateUrl) &&
        Objects.equals(this.webhookOnStatusUpdateEnabled, v0PlaybooksBody.webhookOnStatusUpdateEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, teamId, createPublicPlaybookRun, _public, checklists, memberIds, broadcastChannelIds, invitedUserIds, inviteUsersEnabled, defaultOwnerId, defaultOwnerEnabled, announcementChannelId, announcementChannelEnabled, webhookOnCreationUrl, webhookOnCreationEnabled, webhookOnStatusUpdateUrl, webhookOnStatusUpdateEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V0PlaybooksBody {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    createPublicPlaybookRun: ").append(toIndentedString(createPublicPlaybookRun)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    checklists: ").append(toIndentedString(checklists)).append("\n");
    sb.append("    memberIds: ").append(toIndentedString(memberIds)).append("\n");
    sb.append("    broadcastChannelIds: ").append(toIndentedString(broadcastChannelIds)).append("\n");
    sb.append("    invitedUserIds: ").append(toIndentedString(invitedUserIds)).append("\n");
    sb.append("    inviteUsersEnabled: ").append(toIndentedString(inviteUsersEnabled)).append("\n");
    sb.append("    defaultOwnerId: ").append(toIndentedString(defaultOwnerId)).append("\n");
    sb.append("    defaultOwnerEnabled: ").append(toIndentedString(defaultOwnerEnabled)).append("\n");
    sb.append("    announcementChannelId: ").append(toIndentedString(announcementChannelId)).append("\n");
    sb.append("    announcementChannelEnabled: ").append(toIndentedString(announcementChannelEnabled)).append("\n");
    sb.append("    webhookOnCreationUrl: ").append(toIndentedString(webhookOnCreationUrl)).append("\n");
    sb.append("    webhookOnCreationEnabled: ").append(toIndentedString(webhookOnCreationEnabled)).append("\n");
    sb.append("    webhookOnStatusUpdateUrl: ").append(toIndentedString(webhookOnStatusUpdateUrl)).append("\n");
    sb.append("    webhookOnStatusUpdateEnabled: ").append(toIndentedString(webhookOnStatusUpdateEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
