/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * V4ChannelsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class V4ChannelsBody {
  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("purpose")
  private String purpose = null;

  @JsonProperty("header")
  private String header = null;

  @JsonProperty("type")
  private String type = null;

  public V4ChannelsBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The team ID of the team to create the channel on
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public V4ChannelsBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The unique handle for the channel, will be present in the channel URL
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V4ChannelsBody displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The non-unique UI name for the channel
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public V4ChannelsBody purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * A short description of the purpose of the channel
   * @return purpose
  **/
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public V4ChannelsBody header(String header) {
    this.header = header;
    return this;
  }

   /**
   * Markdown-formatted text to display in the header of the channel
   * @return header
  **/
  public String getHeader() {
    return header;
  }

  public void setHeader(String header) {
    this.header = header;
  }

  public V4ChannelsBody type(String type) {
    this.type = type;
    return this;
  }

   /**
   * &#x27;O&#x27; for a public channel, &#x27;P&#x27; for a private channel
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4ChannelsBody v4ChannelsBody = (V4ChannelsBody) o;
    return Objects.equals(this.teamId, v4ChannelsBody.teamId) &&
        Objects.equals(this.name, v4ChannelsBody.name) &&
        Objects.equals(this.displayName, v4ChannelsBody.displayName) &&
        Objects.equals(this.purpose, v4ChannelsBody.purpose) &&
        Objects.equals(this.header, v4ChannelsBody.header) &&
        Objects.equals(this.type, v4ChannelsBody.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamId, name, displayName, purpose, header, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4ChannelsBody {\n");
    
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
