/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * V4CommandsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class V4CommandsBody {
  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("method")
  private String method = null;

  @JsonProperty("trigger")
  private String trigger = null;

  @JsonProperty("url")
  private String url = null;

  public V4CommandsBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Team ID to where the command should be created
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public V4CommandsBody method(String method) {
    this.method = method;
    return this;
  }

   /**
   * &#x60;&#x27;P&#x27;&#x60; for post request, &#x60;&#x27;G&#x27;&#x60; for get request
   * @return method
  **/
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }

  public V4CommandsBody trigger(String trigger) {
    this.trigger = trigger;
    return this;
  }

   /**
   * Activation word to trigger the command
   * @return trigger
  **/
  public String getTrigger() {
    return trigger;
  }

  public void setTrigger(String trigger) {
    this.trigger = trigger;
  }

  public V4CommandsBody url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL that the command will make the request
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4CommandsBody v4CommandsBody = (V4CommandsBody) o;
    return Objects.equals(this.teamId, v4CommandsBody.teamId) &&
        Objects.equals(this.method, v4CommandsBody.method) &&
        Objects.equals(this.trigger, v4CommandsBody.trigger) &&
        Objects.equals(this.url, v4CommandsBody.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamId, method, trigger, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4CommandsBody {\n");
    
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
