/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.File;
/**
 * V4EmojiBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class V4EmojiBody {
  @JsonProperty("image")
  private File image = null;

  @JsonProperty("emoji")
  private String emoji = null;

  public V4EmojiBody image(File image) {
    this.image = image;
    return this;
  }

   /**
   * A file to be uploaded
   * @return image
  **/
  public File getImage() {
    return image;
  }

  public void setImage(File image) {
    this.image = image;
  }

  public V4EmojiBody emoji(String emoji) {
    this.emoji = emoji;
    return this;
  }

   /**
   * A JSON object containing a &#x60;name&#x60; field with the name of the emoji and a &#x60;creator_id&#x60; field with the id of the authenticated user.
   * @return emoji
  **/
  public String getEmoji() {
    return emoji;
  }

  public void setEmoji(String emoji) {
    this.emoji = emoji;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4EmojiBody v4EmojiBody = (V4EmojiBody) o;
    return Objects.equals(this.image, v4EmojiBody.image) &&
        Objects.equals(this.emoji, v4EmojiBody.emoji);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(image), emoji);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4EmojiBody {\n");
    
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    emoji: ").append(toIndentedString(emoji)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
