/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.your.mattermost.url.client.Apiv4groupsGroup;

import java.util.ArrayList;
import java.util.List;
/**
 * V4GroupsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class V4GroupsBody {
  @JsonProperty("group")
  private Apiv4groupsGroup group = null;

  @JsonProperty("user_ids")
  private List<String> userIds = new ArrayList<>();

  public V4GroupsBody group(Apiv4groupsGroup group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  public Apiv4groupsGroup getGroup() {
    return group;
  }

  public void setGroup(Apiv4groupsGroup group) {
    this.group = group;
  }

  public V4GroupsBody userIds(List<String> userIds) {
    this.userIds = userIds;
    return this;
  }

  public V4GroupsBody addUserIdsItem(String userIdsItem) {
    this.userIds.add(userIdsItem);
    return this;
  }

   /**
   * The user ids of the group members to add.
   * @return userIds
  **/
  public List<String> getUserIds() {
    return userIds;
  }

  public void setUserIds(List<String> userIds) {
    this.userIds = userIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4GroupsBody v4GroupsBody = (V4GroupsBody) o;
    return Objects.equals(this.group, v4GroupsBody.group) &&
        Objects.equals(this.userIds, v4GroupsBody.userIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(group, userIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4GroupsBody {\n");
    
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    userIds: ").append(toIndentedString(userIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
