/*
 * Mattermost API Reference
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.your.mattermost.url.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * V4UploadsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-15T16:32:52.937863200+07:00[Asia/Saigon]")
public class V4UploadsBody {
  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("filename")
  private String filename = null;

  @JsonProperty("file_size")
  private Long fileSize = null;

  public V4UploadsBody channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The ID of the channel to upload to.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public V4UploadsBody filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * The name of the file to upload.
   * @return filename
  **/
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public V4UploadsBody fileSize(Long fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * The size of the file to upload in bytes.
   * @return fileSize
  **/
  public Long getFileSize() {
    return fileSize;
  }

  public void setFileSize(Long fileSize) {
    this.fileSize = fileSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4UploadsBody v4UploadsBody = (V4UploadsBody) o;
    return Objects.equals(this.channelId, v4UploadsBody.channelId) &&
        Objects.equals(this.filename, v4UploadsBody.filename) &&
        Objects.equals(this.fileSize, v4UploadsBody.fileSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, filename, fileSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4UploadsBody {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
