# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  mattermost:
    baseUrl: "http://host.docker.internal:8065"
    accessToken: "apk7xupc4fbcxcqskb79qn5uww"
    teamName: "AxonIvy"
    botName: "axonivy-bot"
    notification:
      # enables the Mattermost notification for new tasks
      enabled: true
      # the message of new task will be sent to channel
      newTaskMessage: "The new task %s is created."